### ISSUE TITLE
"click and run" Windows installation

### ISSUE THREAD

**Issue by mfrasca** [Ghini/ghini.desktop#109]
_From @mfrasca on October 24, 2015 16:12_

quite rightfully, Ross Demuth writes:

> The windows installation process needs to be a lot simpler or people will not even try it out

_Copied from original issue: Bauble/bauble.classic#155_

**Comment by mfrasca** [comment]
see #219

**Comment by mfrasca** [comment]
author @takluyver has written [pynsist](https://github.com/takluyver/pynsist), specifically thought to build Windows installers for Python applications, and it even has a [gtk example](https://github.com/takluyver/pynsist/tree/master/examples/pygtk). I only do not manage to find the time to test it. (actually, I first need to grab a Windows machine, a powerful antiemetic, then I can learn how to do this.)

**Comment by takluyver** [comment]
Hi! Coincidentally, I have a background in plant science, so I'm happy to see you're thinking of using Pynsist for this. Feel free to ping me with any questions you have.

It sounds like you have an aversion to Windows, so you may be pleased to know that Pynsist can build installers from Linux/Mac. You'll still need to use Windows a bit as you're figuring out how to make a working installer, but once it's set up, it's totally possible to build installers for new minor versions without running Windows.

The trickiest bit is getting the necessary files for pygtk in the right place. The `grab_files.sh` script in the gtk example deals with this, so long as the URLs it downloads from haven't changed since I wrote it.

**Comment by mfrasca** [comment]
Hi @takluyver . things sometimes meet nicefully. I will be able to use a Windows machine in a couple of weeks, possibly (or, إن شاء الله‎‎, as people here say.)
do I understand you correctly, that I would first need set it up on such a machine, then, that is once I'm sure it works, I can produce a one-click-installer executable file from my linux system?

**Comment by takluyver** [comment]
Yep, that's right. In fact, you can do even the initial setup from Linux, but it's a good idea to test the first installers on a Windows machine to make sure they're not missing anything.

**Comment by brettatoms** [comment]
If it helps there was an NSIS installer script that worked at some point: https://github.com/Ghini/ghini.desktop/blob/master/scripts/build.nsi

**Comment by RoDuth** [comment]
Let me know if you want me to test on my win 10 set up.

**Comment by mfrasca** [comment]
thank you all for the input. the NSIS installer script, I'm aware of it and it's not practical because I would need a windows machine to run it, isn't it? the pynsist would allow me set things up once and for all and then create the installer without having the windows machine I do not have.
sorry for the delay, I do not have the time to look into anything, at least for a couple more weeks.

**Comment by takluyver** [comment]
The NSIS script could also be run on a non-Windows machine. This is actually what Pynsist relies on: it generates a NSIS script using a template, and then runs it to build the installer. The NSIS builder can run on non-Windows platforms (on Debian/Ubuntu, run `sudo apt-get install nsis`).

**Comment by mfrasca** [comment]
oh, I was not aware of that. seems I need to review the whole thing then. :worried:

**Comment by mfrasca** [comment]
@takluyver do you have time to assist me any soon, I want to close this one, and I'm not many steps further, all the work done by @RoDuth I never managed to apply on my machine, he's probably got something installed or configured that makes things go smooth, but we don't know what that is.

**Comment by takluyver** [comment]
Oh hi, I'd entirely forgotten about this. :-)

I'm happy to try to help, but I've never worked with the classic pygtk, which I see you're using, and I've always found Gtk one of the most inconvenient frameworks to distribute. So I might not be much help.

Where are you currently getting stuck?

**Comment by mfrasca** [comment]
I'm right now busy porting to Gtk3, away from PyGTK, because of #330, and of the imminent end-of-life for Python2.  Still 5 errors, 5 failures out of 562 unit tests.
stuck where? in [the documentation](http://ghini.readthedocs.io/en/ghini-1.0-dev/building.html#distributing-for-windows), I do not manage to follow the steps described there.
if you want to give it a try, the most relevant branch would be `ghini-gtk2-3`
I might disappear from time to time, I'm at un unstable connection.
if you want a chat-line, we can do irc, or telegram, or whatever, just give me your coords per email.

**Comment by RoDuth** [comment]
Can I ask @mfrasca have you actually tried what is documented using the `ghini-1.0` branch?  I have repeated those steps as they are described on many systems without issue.  What are you actually having trouble with?  I'm happy to help update it and glad to see your finally upgrading python2 and gtk but I have lost my patients for repeatedly going over the basic steps in producing an installer.

If you wish it to include the windows installer in your `publish.sh` script then you'll have limited options as a working install of windows is required for py2exe I believe.  I had little luck with Wine. Running the script in windows using Windows Subsystem for Linux may be an option.  I'd be inclined to suggest VBoxManage and a VirtualBox VM to automate the process.  As I've stated before I have a VM setup with the folder where I have ghini set as the shared drive and I run the installer script from there using a snapshot taken at the point where `scripts\build_win.bat` is on the command prompt but not entered yet.  All I have to do is fire up the VM press enter and close it and there is an installer in the `scripts` folder.  That's not a lot to automate with VBoxManage.  Also I don't have to install git on the VM and just use the linux host system to do everything other than build the installer.

I'm happy to help with all this but not if I'm wasting my time and effort again.  You have repeatedly stated that you are unable to produce an installer using my instructions.  Without specifics and I can only assume you have never really tried.  Please @takluyver can you have a go at following the instructions (for the `ghini-1.0` branch and see if I have missed something.

**Comment by mfrasca** [comment]
@RoDuth , you got the point: indeed I »wish to include the windows installer in [our] `publish.sh` script« and from @takluyver I understand that that's possible.  
the rest of your sentence »then you'll have limited options as a working install of windows is required for py2exe *I believe*«, I find puzzling, since I only run `publish.sh` from a bash shell within Linux, where does my (not always available) working install of Windows fit in the process?
Anyhow, this is the [win-build.log](https://github.com/Ghini/ghini.desktop/files/2036149/win-build.log), running your Windows script, which does not produce any `exe` file, yet.

**Comment by mfrasca** [comment]
> the libraries needed for Gtk […] work out which packages are needed, where to get them from, and how to arrange the files for the installer

You are not referring to what's installed by `pip`, you're thinking of the binary libraries needed by `Gtk`, right?
After I'm done moving towards Gtk3 and away from PyGTK, I'm afraid that my current installation instructions for Windows aren't valid any more and I have to review them.

I'm sorry to admit: I do not have the energy to sit at a Windows playstation and try to get work done on a system which does all that is conceivable to be incompatible with Unix.  in particular not while I have other more interesting tasks at hand, like projects [`2`](https://github.com/orgs/Ghini/projects/2?fullscreen=true) and [`3`](https://github.com/orgs/Ghini/projects/3?fullscreen=true).  I wish I had money to pay a worker do that, but I haven't.

**Comment by mfrasca** [comment]
> @mfrasca I don't see a ghini-gtk2-3 branch in the branches list, but it looks like you've been working on the ghini-3.1-dev branch recently. Is that it?

yes, sorry, I first mentioned, then renamed.  it was part of [project 3](https://github.com/orgs/Ghini/projects/3?fullscreen=true).

**Comment by RoDuth** [comment]
I would say you have installed a different versions of NsisMultiUser plugin.  See minor change to nsis script.  Thanks for trying and providing details.  Let me know if that doesn't work for you.

**Comment by mfrasca** [comment]
as it stands now, at least on the Windows machine I can use, which has a long history of attempts at this goal, well, as it stands now it runs and produces an installer and it gathers `dll` and `pyd` files which I guess can be used from Linux, if I understood what @takluyver is saying.

but, as it stands, it does not respect file organization, since the product (eg: `ghini.destktop-1.0.83-setup.exe`) is written in the `scripts` directory, and all the temporary files end up in the `dist` directory, while I would expect the product in `dist` and the temporary files somewhere in `build`, or in an other directory, clearly recognizable as a temporary directory.

it would be interesting to know which steps were really necessary and would be sufficient to prepare a machine to running `build-win`, and I think it is urgent to make sure that:

- [ ] the product goes in `dist`
- [ ] temporary files do not end up cluttering `dist`
- [ ] the branch name becomes part of the virtual environment name (like `ghi2exe-1.0` / `ghi2exe-3.1`)

**Comment by RoDuth** [comment]
> it would be interesting to know which steps were really necessary and would be sufficient to prepare a machine to running build-win, and I think it is urgent to make sure that:

As stated in the documentation it really is just install Python 2.7, PyGTK and NSIS v3, git, clone the repo and checkout the branch you want to work with.

> the branch name becomes part of the virtual environment name

easy enough I guess but so you know, as it states in the docs, you can specify a virtual environment location with something like `scripts\build_win.bat ..\ghi2exe` or whatever you wish.

> but, as it stands, it does not respect file organization, since the product (eg: ghini.destktop-1.0.83-setup.exe) is written in the scripts directory, and all the temporary files end up in the dist directory, while I would expect the product in dist and the temporary files somewhere in build, or in an other directory, clearly recognizable as a temporary directory.

I can not see the issue.  It has nothing to do with `build-win.bat` or anything I have done.  `dist` is where py2exe places it files and the nsis installer ends up in the same directory as the `.nsi` file it is built from.  This seems perfectly reasonable to me.  I think your over thinking `build-win.bat`, it really is, as stated in the documentation, a minimal script that essential just runs:
```
virtualenv --system-site-packages <path-to-venv>
call <path-to-venv>\Scripts\activate.bat
pip install psycopg2 Pygments py2exe_py2
pip install .
python setup.py py2exe
python setup.py nsis
```

I wouldn't want it to more than that.

> by the way: what is this data/nsis stuff?

these are the plugins as used in the nsis script to build the installer.  They are all at the version the script was built on. By including them you no longer have to do anything to setup the nsis environment to build in nor should you have any issues with breaking changes to newer versions etc.. I'll change the location in the scripts to your new location later tonight.

Glad you are finally looking at this.  Considering that I had done the majority of this over 18 months ago and made improvements and documented it well over 6 months ago.

**Comment by takluyver** [comment]
I'm an outside observer on this project, but I know from other projects how easy it is to get busy and let contributions linger, especially when they relate to something that doesn't directly impact us (like Windows packaging for a habitual Linux user like me). I also know how frustrating it can be to make contributions which then go unreviewed and unused. But at the end of the day, getting snippy about it doesn't help anyone. These things happen.

**Comment by RoDuth** [comment]
Point taken but I guess I feel the same about  (among others):
> this nicely written piece of prosa in the documentation.

Having put a lot of my own time into writing that documentation...

**Comment by mfrasca** [comment]
@RoDuth , getting sour doesn't help anyone.  You know I review your texts, I have accepted your contributions (and in the end I was too optimist about them, they have generated surprises and days of cleaning up and trouble with our few users).  To my experience and judgement, your texts are even longer than mine, which are already wordy, don't mention things in the needed order, miss "obvious" steps.  I am forgetful, I'm not a Windows user, I do not know what is "obvious" in Windows (not even in Linux).

> I wouldn't want [the script] to be more than that.

Maybe here is the main difference, why we don't understand each other.  I do need scripts to be complete, something I can count upon, that they do what they are expected to do, and that do it according to the organization of the rest of the software.  I just want to be able to start it and not need to manually clean things up after it.  that's the whole idea of software, according to me.

**Comment by mfrasca** [comment]
anyhow, I now have, a bit intermingled with other files in the `dist` folder, all the intermediate files that *maybe* could help us produce a setup.exe from Linux.  is this what @takluyver was saying?

(we have a running ghini.desktop using Gtk3/Python3, and it shows maps from osm.org)

**Comment by mfrasca** [comment]
> I'll change the location in the scripts to your new location later tonight and have a look at the branch name/virtual environment issue... 

:+1:

**Comment by takluyver** [comment]
Yup, if you can get all the files together in the state just before `setup.py` calls `makensis`, that final step can be done on Linux. However, I think any change to the code will require re-running py2exe, which as far as I know has to be done on Windows.

The realisation that led to Pynsist was that you don't actually need to freeze the code and make a file like `ghini.exe`. Users are going to launch it from a start menu shortcut anyway, and you can make a shortcut that runs something like `...\pythonw.exe ...\ghini.py`. So the installer packs your packages and modules along with a prebuilt copy of Python. But the tricky bit, as you already said, is finding and arranging binary dependencies like DLLs.

If @RoDuth's solution is mostly working, it may be best for you to stick with that and not get sidetracked trying to build Windows installers from Linux - it is a handy feature, but after any major changes it's best to test the installer on a Windows machiner anyway. Getting a working installer with Gtk is hard enough that if you've got one way to do it, I'd keep it. ;-)

**Comment by takluyver** [comment]
The difference is that your shortcut points to `ghini.exe`, which is built by py2exe (this is based on what I can see in `build-multiuser.nsi` - I haven't tried it out). I'm suggesting that an alternative is to have a shortcut that runs something like `python.exe ghini.py`, and not use py2exe at all. That makes it possible to change the code in ghini and rebuild the installer from Linux.

But that change would be some extra work, so it may be easier to just accept that Windows installers are built on Windows. It depends how often you're likely to need to build installers, and how painful using Windows is.

**Comment by mfrasca** [comment]
to the question "how often likely to build an installer": three years ago we were at `bauble-1.0.11`, now we are at `ghini.desktop-1.0.83`, so that's in average once every two weeks.  my point of view is that if it isn't automated, I will forget using it, or how to use it.  so I now have a script that does everything associated to publishing to the production branch: merge development into production, giving the merge commit a meaningful comment, bump version, commit the bump, push to github, build a debian package, verify it still matches the terribly strict quality checks by debian, push the package to `mentors`, push the new release to pypi, and I wish to do also the windows installer, never mind if I have to push it to github by hand, but the goal would be to automate that, too.  (but the part regarding debian we still need to seriously review)

this way, if I also document the procedure, like "please use this script", and the script is consistently commented, then who knows, the next maintainer of this project will not need to reinvent the wheel.

apart from all the above consideration: **I would VERY much prefer a Windows installer that does not compile the python sources!**

actually, would it mean that the windows sources could stay in a git checkout?  that would allow us produce only ONE initial Windows installer, and let user update by `git pull`, just like we do on a "normal" installation.

**Comment by RoDuth** [comment]
I've said it before I believe you could produce an nsis installer to do what you would describe but that wouldn't work for me.

Issue for me is that the government department in charge of the botanic garden has a very restricted environment (as most do in Australia, New Zealand and no doubt its similar in many others parts of the world).  They flatly do not allow git, internet access is limited (I still haven't been able to get them to allow ghini access for the plant list name check function for instance), they prefer no full python install also.  They allow 1 or 2 shared terminals to have global installs of ghini and all others to have per user installs.  Also everything must be able to be remote deployed silently.  For them almost everything is now deployed on servers and accessed by web browsers, thin clients, remote desktops, etc. with  most of that largely run remotely by contractors who take responsibility for the security etc.  Ghini in a remote desktop is a pain if you ask me.  As it stands they would not be in for running a fresh installer every 2 weeks so I have to be strategic about it.  This is what has had me looking again at [collectionspace](http://www.collectionspace.org/) or @brettatoms bauble.web (neither are ideal).

if you wish to just have it automated in linux then what is wrong with a VM and VBoxManage? Its simple enough from what I can gather.  Would be happy to give it a try.  I spend 98% of my time on linux and as little as possible in windows, most of that in a linux hosted VM.

There are other benefits to the py2exe, NSIS combination that Brett chose to use.  It really does compress things quite a lot for instance.  I think I got rid of most of the excess but no doubt it could be improved further.  And it could be possible to have smaller changes made as a patch release.

**Comment by takluyver** [comment]
Even besides the issues with locked down systems, I think an install that you update by doing `git pull` is not terribly practical. Your initial installer would need to install git and ensure it's on PATH, and you'd need extra steps if you ever wanted to add or update a dependency.

Another option for automation would be to use [Appveyor](https://www.appveyor.com/) to host Windows continuous integration. I see you already have config for Travis CI; Appveyor is the same kind of service, but with Windows servers. You can get it to build any version with a tag and make the result available for download.

**Comment by mfrasca** [comment]
we indeed need git, and we do need it in the PATH, and `git pull` is indeed followed by `python setup.py install`.  I do git merge && git push (actually `publish.sh`), and that's all I need, users will see the software informing them they can update, and they have a script to do that.
I'll check www.appveyor.com … do you know whether they can push files from their server back to git?  in that case, when it runs our tests on the production branch, it could even conclude a successful test with the windows builder, commit and push to github.  like `travis-ci` lets you do, for example, to produce `lektor` web sites on git pages.

**Comment by takluyver** [comment]
Looks like it has support for [uploading to Github releases](https://www.appveyor.com/docs/deployment/github/). I don't think there's built-in support for pushing to git - storing large binary files in git is generally not recommended. But if you really want installers to go into a git repository, you can configure it with arbitrary commands to do that.

**Comment by RoDuth** [comment]
@mfrasca You may need git but no one I work with can use it, are you sure you wish to alienate them?  Just spent a few moments looking into Appveyor and so far it looks great.  Thanks @takluyver for the ref.

**Comment by RoDuth** [comment]
as for including in the path that is the reason for the visual basic script `add_to_path.vbs` and you are welcome to use it.  Drawing from my aging memory.. apparently anything batch file wise is likely to stuff your PATH up because of it's limits on length of a string or something along those lines... Apart from the fact that I really wasn't comfortable with writing VB I do remember putting this in the scripts comments if you do wish to use it:
```

' a simple script used by the nsis installer to prepend to the PATH
'
' EXAMPLES:
' cscript.exe Add_to_PATH.vbs /path:"C:\TEST" /env:"USER"
' cscript.exe //E:vbscript Add_to_PATH.vbs /env:"SYSTEM" /path:"C:\TEST\"
```

**Comment by takluyver** [comment]
> are you interested in having all necessary permission for doing this part?

Me? Not really, sorry! I've got too many projects on the go already that I'm trying to find time to work on. I'm happy to continue answering questions and providing pointers.

I think that having end users pull updates with git, even through a wrapper script, would probably cause you more pain in the long run. It's impractical for updating any computer that's not on the internet, and it's hard to debug when something goes wrong.

**Comment by mfrasca** [comment]
> Me? Not really, sorry!

never mind, one asks, just in case.

>pull updates with git […] pain in the long run.

my experience with it was quite the opposite, you do need at least one user able to run a command from the command prompt, but then they can help tracing back errors, when something goes wrong.  it's been more a help factor than a burden.

the whole `python setup.py install` is based on `pip install` and relies on being on the internet, and that yes has been a problem in several cases.  … well, however, if we first exclude those where they had no permission to install anything anyway, it was at one station somewhere in Peruvian Amazonas.

**Comment by takluyver** [comment]
Your call, of course, but I think @RoDuth is pointing out that internet restrictions at their institution would cause issues, even if it's not deep in the Amazon. Given what Ghini does, I'd imagine that it's not unusual for potential users to be in similar institutional environments.

**Comment by mfrasca** [comment]
I think that offering both ways is a good option.  I have a user who's unable to install because, well, I have not the faintest idea, they just panic and can't tell me where it goes wrong.  so a 'click and run' would be the only option in such cases.

**Comment by mfrasca** [comment]
so, apart from me not understanding what was going on because of mismatched labels, we have a perfectly functional tool for producing both: a windows installer; a windows relocatable runtime.
I think I would only like to find the windows installer in the `dist` directory (ends now in `scripts`), and the windows relocatable runtime in a new directory that suggests this usage, something like `ghini-runtime` maybe, or `copy-me-to-a-usb-drive`, (ends now in `dist`, which gets previously completely emptied, possibly not completely desirable).

**Comment by mfrasca** [comment]
2b2c47f940e849bacab2073f487fa30c068d4b75
bb38fa0575b52e430c841f307c9bb51ee3554dd2
243c32c0560ec9e851dcf73a7e1f9f5c24152cd6
74919efd852e8af54b640b97d12150e5222c6ea8
a6a8f5dca4407ef1453b786bf2183806bdf5b08a

**Comment by mfrasca** [comment]
does any of you know how to solve windows issues like:
`WindowsError: [Error 32] The process cannot access the file because it is being used by another process`
we get quite a bunch of them on AppVeyor.
https://ci.appveyor.com/project/mfrasca/ghini-desktop

**Comment by takluyver** [comment]
It looks like it's an error from a file being deleted during teardown of a test. On Windows, you have to ensure that a file is closed before deleting it. In some situations you can also only have a file open in one place at once.

Looking at the code which is failing the tests, one possible culprit is this pattern:

```python
result = json.load(open(self.temp_path))
```

That's relying on garbage collection to close the file, which may not happen until after the teardown tries to remove it. Try replacing those instances with:

```python
with open(self.temp_path) as f:
    result = json.load(f)
```

**Comment by mfrasca** [comment]
It's more than the above, and there are subtle differences. see #384.
