### ISSUE TITLE
review NSIS installer build.nsi

### ISSUE THREAD

**Issue by mfrasca** [Ghini/ghini.desktop#126]
_From @mfrasca on December 13, 2015 12:37_

`scripts/build.nsi` is a remnant of the previous "battery included" installer.
is it possible to have it do the same as the current batch-files-based installation procedure?
so that the instructions could be reduced to "download and run the installer"?

_Copied from original issue: Bauble/bauble.classic#219_

**Comment by mfrasca** [comment]
check [pynsist](https://github.com/takluyver/pynsist)

**Comment by RoDuth** [comment]
I _think_ it may be possible to make an nsis installer that could follow the steps to do the batch file install.  It occurred to me while I was building the current mulituser version that it should be possible.  Would take some work but I think it could be achieved.  But this wouldn't work in the situations I've needed the installer for - network and security restricted in government settings

**Comment by mfrasca** [comment]
reviewing the things to do, and I see this one, which is related to distributing for Windows. Since you've been working at this, I put it on your name. feel free to close if you think so.

**Comment by mfrasca** [comment]
but why are there so many issues on the same topic?
#109
