### ISSUE TITLE
Species editor dialogs don't display on Mac

### ISSUE THREAD

**Issue by mfrasca** [Ghini/ghini.desktop#139]
_From @brettatoms on January 15, 2016 12:34_

On a fresh install on the Mac when trying to open the species editor all that is displayed is the titlebar.  Maximizing it doesn't show the window.  When you un-maximize the editor flashes open for a second and then collapses again into the titlebar.  See screenshot.

Only tried on Mac 10.11.2

<img width="964" alt="screen shot 2016-01-15 at 7 29 56 am" src="https://cloud.githubusercontent.com/assets/332554/12353144/0a41015c-bb5a-11e5-86f1-6b14e8319d15.png">

_Copied from original issue: Bauble/bauble.classic#278_

**Comment by mfrasca** [comment]
interesting. you have any logging information? when it flashes open "for a second", is it correctly populated? can you grab the base line of the window and pull it open? does this only happen for the species editor?

**Comment by mfrasca** [comment]
I also see that on Mac you have the same problem as I have on the N900, that is that some icons do not show correctly.

**Comment by mfrasca** [comment]
_From @brettatoms on January 15, 2016 12:55_

When it flashes open I can see some text fields but it's too fast to tell what's there and what's not.  No, I can't grab the window handles and drag it open.  Yes, only for the species editor.

See logs:

[b.log](https://files.zenhub.io/5698ebccbff27b8f1afe7186)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)

**Comment by mfrasca** [comment]
I can't see anything strange in the log. as soon as I can access a macintosh, I will have a look at this. who knows this is related to the osx version, and who knows it gets solved once we have a solution to #169 (native look)?

**Comment by mfrasca** [comment]
_From @RoDuth on January 16, 2016 2:46_

Just thought I'd have a quick look on my wife's MacBook Air, OSX v10.9.5.   I installed Bauble on it some time back as a bit of an experiment.  After running the Bauble upgrade (to v1.0.55) I got the same issue with the species editor.  Everything else seemed to be running OK and the species editor was fine previously in v1.0.52.

**Comment by mfrasca** [comment]
ok, in the meanwhile if you need it you know where to roll it back to. if either of you could bisect further so I know when I introduced the problem.

**Comment by mfrasca** [comment]
_From @RoDuth on January 17, 2016 3:0_

seems to be between these 2 commits:
```
commit 3b9452780fdf50c3214f2b8de811c5b3aa787d1f
Author: Mario Frasca <mario@anche.no>
Date:   Fri Dec 4 09:56:25 2015 -0500

    closes #197

commit 0049c3f6d69430aec6b227b8f1dc72ad1e3aa35c
Author: Mario Frasca <mario@anche.no>
Date:   Thu Dec 3 16:38:57 2015 -0500

    closes #52
```

It works at 0049c3f6d69430aec6b227b8f1dc72ad1e3aa35c not at 3b9452780fdf50c3214f2b8de811c5b3aa787d1f

**Comment by mfrasca** [comment]
nice job, thanks. I will have a look at it.
(on github you do not shorten commit hashes, it's github doing that, and it links it to the correct place)

**Comment by mfrasca** [comment]
this 3b9452780fdf50c3214f2b8de811c5b3aa787d1f was a very isolated patch. you could undo it temporarily, or see how to make the mac understand the width hint without collapsing the window height.

**Comment by carlablack** [comment]
/Users/carla/.virtualenvs/ghide/lib/python2.7/site-packages/bauble-1.0.62-py2.7.egg/bauble/utils/__init__.py:739: GtkWarning: gtk_cell_layout_set_attributes: assertion 'GTK_IS_CELL_RENDERER (cell)' failed
  combo.props.text_column = 0

**Comment by carlablack** [comment]
we rolled back that single commit and the program runs, on OSX 10.12

**Comment by carlablack** [comment]
![screen shot 2016-10-13 at 2 33 05 pm](https://cloud.githubusercontent.com/assets/22802234/19363893/8c1e07a6-9151-11e6-9d89-b561bb5ee7f1.png)

**Comment by mfrasca** [comment]
also check this one, it is relevant to the intentions of the incriminated patch.
in particular, the first comment to the first answer.
http://stackoverflow.com/questions/12218970/gtk-label-wrapping-in-a-dialog
