### ISSUE TITLE
have a serious look at collectionspace

### ISSUE THREAD

**Issue by mfrasca** [Ghini/ghini.desktop#144]
@RoDuth reminded me of the existence of [a project called CollectionSpace](http://www.collectionspace.org/). they now seem to have [a botanic garden option](http://botgarden.collectionspace.org/collectionspace/ui/botgarden/html/index.html).
have a look at it, and consider the implications and possibilities.

**Comment by mfrasca** [comment]
@RoDuth

**Comment by fruit-github** [comment]
I had a quick look, demo doesn't work in konqueror but OK in Iceweasel.
Looks to be quite a heavyweight install compared to ghini and not convinced I'd want to try it on my everyday desktop machine.

**Comment by RoDuth** [comment]
Too heavyweight and overly complicated for my needs!

**Comment by mfrasca** [comment]
thanks you both, closing the issue.
