### ISSUE TITLE
did things change on theplantlist?

### ISSUE THREAD

**Issue by mfrasca** [Ghini/ghini.desktop#147]
I'm trying to use the plant list checker and it does not work, all I get is a 'no match'.
maybe I did not enter data which was good enough,
or the interaction on the web service changed,
please check, this is an important tool!

**Comment by RoDuth** [comment]
Yep. Something is up.  Not working here either

**Comment by mfrasca** [comment]
seems it was just their server not servicing. it's all ok now.
but our client should be able to inform us it can't use the service, instead of misleading with 'no results'.

**Comment by fruit-github** [comment]
I noticed they had database issues a short while ago but got fixed.

I have had an issue adding a species more recently that I think should have given a result from the green button. Adding Gymnocalycium damsii, reponse is..
No match found on ThePlantList.org
yet searching ThePlantList.org gives http://www.theplantlist.org/tpl1.1/search?q=Gymnocalycium+damsii

Perhaps that is expected for a similar result?

**Comment by mfrasca** [comment]
you can run the same code that ghini uses by:
* activate the virtual environment
* move to the directory holding the plants plugin sources
* invoke `python ask_tpl.py`
* enter a binomial name (or part of it)
* enter an empty line to end

**Comment by mfrasca** [comment]
hi @fruit-github , seems that your Gymnocalycium damsii gives a result that refers to an accepted form that is not in the database. you can see it also in the web query you post.
`ask_tpl` is a bit too simple and it assumes that the database is consistent. so when looking up the accepted form it does not contemplate the case "the accepted form is not in the database". and it crashes.

**Comment by fruit-github** [comment]
I see. 
I wondered if it was changed behavious in TPL database or front end as it is the first time I have seen that response.
As long as it is working most of the time it is not really a problem to do a manual lookup once in a while :)

Thanks

**Comment by mfrasca** [comment]
quick solution to your case:

    @@ -105,7 +105,15 @@ class AskTPL(threading.Thread):
                 else:
                     raise NoResult
                 if found['Accepted ID']:
    -                accepted = ask_tpl(found['Accepted ID'])[0]
    +                logger.debug("found this: %s", str(found))
    +                accepted = ask_tpl(found['Accepted ID'])
    +                logger.debug("ask_tpl on the Accepted ID returns %s", accepted)
    +                if accepted:
    +                    accepted = accepted[0]
    +                else:
    +                    logger.warning("taxon is marked as synonym, but can't "
    +                                   "access accepted form %s", found['Accepted ID'])
    +                    accepted = None
                     logger.debug("%s after second query", self.name)
                 if self.stopped():
                     raise ShouldStopNow('after second query')

**Comment by mfrasca** [comment]
there still is an other limitation with the `ask_tpl`: it does only considers taxonomic information at rank species, and it assumes that TPL returns the species as first entry. we could enhance it so that it also checks authorship for subspecies, varieties, etc..

**Comment by fruit-github** [comment]
I guess it all depends on how far one wants to go. 
It's a very useful tool as is and has worked for me up to now but then I am not a botanist/taxonomist, just a hobbyist with a small collection of plants.
The current weblink feature allows easy lookup of various sources for additional data eg. subspecies, varieties, etc. and that is enough for me

**Comment by mfrasca** [comment]
hi @fruit-github, check again #150: this problem is caused exactly by the fact that the accepted name for your taxon is a subspecies of something else: _Gymnocalycium anisitsii_ subsp _damsii_ (K.Schum.) G.J.Charles

**Comment by fruit-github** [comment]
I already added that manually and linked to Gymnocalycium damsii as a synonym :)

**Comment by mfrasca** [comment]
it was TPL downtime. and the remaining issue is now in #151
