### ISSUE TITLE
Ghini seemed to be unable to "open" anything

### ISSUE THREAD

**Issue by mfrasca** [Ghini/ghini.desktop#148]
in a comment to issue #143 @RoDuth writes:

In the meantime, I did find another Ubuntu 16.04 issue that I had been largely ignoring but finally lost patience with so decided to look into it.  I found a simple solution and so am posting it here for anyone else with a similar problem.  

The issue was: Ghini seemed to be unable to "open" anything. i.e. clicking on "Search Google" did nothing and reports gave a message saying you had to go find them in the /tmp folder.  It turns out that Ghini uses `gnome-open` to open files when a gnome desktop environment is detected. According to [this](http://askubuntu.com/questions/68961/what-can-i-use-instead-of-gnome-open) `gnome-open` has been superseded by `gvfs-open` and in Ubuntu the more desirable approach is to use `xdg-open` both of which I already had on my system.  It looks like the [python desktop package](https://pypi.python.org/pypi/desktop) is the cause and even though there seems to be a latter version than what is included in Ghini it's no different.

So, the simple solution for anyone currently wanting to install Ghini on a ubuntu 16.04 system... 
install libgnome2-bin.

`$ sudo apt install libgnome2-bin`

I just hope it doesn't cause any conflicts! I guess another approach could be to make an executable link? something like `/usr/bin/gvfs-open` > `~/bin/gnome-open`.  Or is it possible to change `gnome-open` to `gvfs-open` in /bauble/utils/desktop.py without causing harm to any other users?  How long ago did `gvfs-open` start getting distributed with gnome systems?

**Comment by mfrasca** [comment]
be aware that the solution must be cross-platform, so we need check what happens on Windows too.

**Comment by RoDuth** [comment]
Update... I just had another look at /bauble/utils/desktop.py, it does actually make reference to `xdg-open` (the version in the link doesn't) it just seems that its the fall back approach if no other environment is found and hence it must be getting caught by one of the other elif solutions (e.g. GNOME) before it gets that far down the list, at least on my system.

As for windows, I don't think it should have any impact as it looks to me like it gets the `os.startfile(url)` method towards the top of the options, before `gnome-open` or `xdg-open` are mentioned.

**Comment by mfrasca** [comment]
on 14.04/gnome, `xdg-open` works fine too. I never installed kde or the other environments, so I don't know what goes on there. I should do so, or I should wait for user feedback. :wink:
