### ISSUE TITLE
install/copy templates for the reports

### ISSUE THREAD

**Issue by mfrasca** [Ghini/ghini.desktop#160]
when you install ghini, you have no report templates properly installed, you have to look for them in either the Local checkout (which is not nice because editing there will stand in the way of future updates) or in the .virtualenv (which is not nice because it will be overwritten by future updates).
it would be better to put them in the `bauble` data directory, that is the default location for sqlite databases and for the pics and for the log file.
the installer should not overwrite existing files.

**Comment by mfrasca** [comment]
while we are at it, we can provide a couple of example templates:
* all plants, with location and species information
* all species, with a summary of the amount of plants referring to it

**Comment by fruit-github** [comment]
Might be a good idea to include reports/templates in a subdirectory to save clutter in /.bauble/ - but perhaps that is your idea too
I am sure more default templates and examples would be welcomed by hobbyist collectors - and perhaps botanists too

**Comment by mfrasca** [comment]
I doubt about the location for this. `~/.bauble` and `AppData\Bauble` are the system locations for application data like the log and the sqlite databases, but these reports should be easy to find for the user, not hidden from view as application data.
where would a user expect (look for) this information?
what about `Documents/Ghini`?

**Comment by fruit-github** [comment]
I hadn't thought about the hidden aspect
/Documents/ is default save location in debian, sounds good to me if other OS are similar

**Comment by mfrasca** [comment]
as of now, the software itself sort of confuses the concepts. it defines a `user_dir` which points to what I just called application data, it does not let the user choose it.
I think I will rename `user_dir` to `application_data_dir` (or maybe something shorter) and add a configuration entry for user data location.
then I will need have a look at the places where we use `user_dir` and decide what we truly need there.

**Comment by mfrasca** [comment]
I think that this is good enough now. the templates are copied into the (hidden) appdata directory, then it's up to the user to copy it to their own documents. Windows does not seem to hold an environment or configuration variable where it declares where are user 'Documents' . xdg based unix distributions hold it in `~/.config/user-dirs.dirs`.
I don't want to put so much complication into the installation script, so I will close it here.
when we address the templates repository issue (#108) we have the chance to solve this part too.
