### ISSUE TITLE
query strings

### ISSUE THREAD

**Issue by Panamagic** [Ghini/ghini.desktop#169]
Hello, is it possible to have somehwere in the help page or forum a place where you put examples of strings to get specific list. Say we expect a specialist Botanist and I would like to show her all the unidentified species in our garden, it would be handy if we had a list of plantings (which inside have the location)...
Something like: 
Open query builder, search under plant, probably sp somewhere and than something with the zzz....

Or a list of direct strings to type whereby you can learn from the examples NOTE I REALLY NEED MARIO TO CHECK THIS BECAUSE THEY MAY BE TECHNICALLY WRONG - I AM TRYING: 
species where genus.family.family like A%        = a listing of all species in families starting with an A
fam like %                                                          = a listing of all families (will take some time)
species where genus like Zzz  
= a listing of species unidentified genus but to get all you have to add something with sp too...

And than I guess I would like to print it or export it together with the accession number as in our case we put the lot number (indication of location) right in there....

Would it be possible while you work on the new and better version of GHINI to have somewhere suggestions for complete query strings and their meaning... 
Thanks
Loes

**Comment by mfrasca** [comment]
I'm afraid I had forgotten this one. what about using a page in the [wiki](https://github.com/Ghini/ghini.desktop/wiki)? it should be open for contribution to any registered github user.

**Comment by mfrasca** [comment]
I opened [this page](https://github.com/Ghini/ghini.desktop/wiki/UsefulQueries), where I put your first hints. if this does not solve the issue, please reopen.

**Comment by Panamagic** [comment]
Seems fine with the wiki page. Since you closed #169 I cannot say thank you there. I also believe that my password is somewhere in Mariato... Would be good if there were way more strings on there. I would not have much capacity to make up strings...
Do you think others have???
Loes
