### ISSUE TITLE
use case: community tree mapping to create an inventory

### ISSUE THREAD

**Issue by hyances** [Ghini/ghini.desktop#175]
we would like to document a process, which is related to using Ghini and openstreetmap.

the idea is to create geographic data with the community:

* each surveyor tag the tree with --at least-- the code number;
* take a geo-picture of the tag;
* take several geo-pictures of the tree --at least-- one with the complete tree;
* botanic experts classify and identify the pictures of each specimen;
* create an OSM "map feature" style wiki page with the species
* create geographic data (by making OSM mapping parties)
* clean and import OSM data to Ghini
* update & manage datasets with Ghini (Silvicultura Urbana)
* Export data to OSM to update open&public data

**Comment by mfrasca** [comment]
Hola Humberto! (escribo en inglés como si fuese de interés general, por cuanto Ghini al momento vive en América Latina, así que también escribir en espanol sería razonable...)
the relevancy of your issue here for ghini is mostly related to the export feature from ghini to OSM.
it is indeed important to know why one would want to export something to OSM, in order to decide how to implement it. what you describe here is a workflow, and in a private telegram message you have suggested we produce a formal description of this workflow on gitbook.com — I had suggested we do so in ghini.github.io or ghini.readthedocs.io — I do not know gitbook.com yet, I'll have a look, but I still prefer to include the workflow as part of ghini's documentation.

**Comment by hyances** [comment]
Hello Mario,

you are right about the domain or taxonomy of the contents; but right now
my focus is to design a methodology to create and manage a citizen/public
tree inventory with OpenStreetMap and Ghini.  This is the reason why I
propose something like gitbook to redact this guide, I'm afraid this is
something out of Ghii documentation, so we can dialogue here (in this
issue) only the topics that involve Ghini.

So let's use this issue to identify where Ghini starts with the process,
I'm wondering by example that could be here:


   - *botanic experts classify and identify the pictures of each specimen;*


I mean, the pictures could be uploaded to Ghini to create the botanical
classify into the database or we can create a wiki that later be used into
a mapathon or we can do this by a Mapping Party with experts or we can
create a task with PyBossa an let that a crowd of experts do that?

Other topic where Ghini can acts could be:


   - *clean and import OSM data to Ghini*


After we have all --or part-- of the inventory mapped, then we can upload a
.osm file to Ghini to create a dataset into Ghini that will be managed
later.

2016-11-23 11:07 GMT-05:00 Mario Frasca <notifications@github.com>:

**Comment by mfrasca** [comment]
I would change the points you give, to:

field work
-------
* each tree receives a unique numerical code, hereafter referred to as "accession code". The accession code is printed on a permanent support and physically attached to the living tree. to do so without damaging the tree, we:
  * print the accession code on an aluminium plate.
  * tie the plate to a strong branch of the tree, using fishing line.
  * alternatively, use aluminium nails to fix the plate to the tree.
* every picture of the tree of parts of the tree includes the accession code.
* take several georeferenced pictures of the tree, at least one with the complete tree;
* optionally, use any well known procedure to help determine the coordinates of the tree (e.g.: field notes, relative positions, alignments, triangulations, ...);

back at office
------------------------
* insert the geographic data in OSM (possibly holding OSM mapping parties)
* each plant is tagged with:
  * accession number; tag to be defined; absolutely do this
  * species (as of current practices)

* insert the accession and plant in a `ghini` database
* each plant with its pictures;
* add the geographic coordinates of the plants as a note
  * category=coords; text=lon;lat (decimal degrees)
* add the OSM object ID as a note to the plant
  * category=OSM_id; text=id
* invite botanic experts to give their opinion about the plant identification;

publishing
---------------------
* Export data to OSM to update open&public data

**Comment by mfrasca** [comment]
have a look here
https://www.gitbook.com/book/mfrasca/identificacion-y-georeferenciacion-de-arboles

**Comment by hyances** [comment]
Well, yesterday I create this... https://www.gitbook.com/book/hyances/inventario-de-arboles-basado-en-openstreetmap-y-g/welcome

So I think your document could be focused on Ghini without the community/citizens part?

**Comment by mfrasca** [comment]
oh, no, no, let's work at the same book, I'm fine with Spanish, but I'm used to answer in the language in which the question was posed... I suggest each of us takes responsibility of (focuses on) a specific aspect, and writes about it. then we provide each other feedback and PUBLISH OFTEN, so we're always aware of the status at the other end.

**Comment by mfrasca** [comment]
403 - can't access

**Comment by hyances** [comment]
I've send you collab invitation, the document need to be published first to
be public avaible...

2016-11-23 12:21 GMT-05:00 Mario Frasca <notifications@github.com>:

**Comment by mfrasca** [comment]
if you make it public immediately, you might find early collaborators.

**Comment by mfrasca** [comment]
(I have a very unreliable connection, I had missed your invitation before I sent out an invitation in the opposite direction)

**Comment by mfrasca** [comment]
I think this is still too loosely related to ghini.desktop, while most of the issue is related to documenting the production of geographic data. Since the process is going to be described, if ever, in one of the two gitbooks we opened, I think there's no need to keep it open here too. Whenever we have a properly described protocol, we will know whether anything is needed in ghini.desktop to implement it.
