### ISSUE TITLE
propagations and new accessions

### ISSUE THREAD

**Issue by mfrasca** [Ghini/ghini.desktop#176]
reading [a document](http://www.botanicgardens.ie/educ/accnosho.pdf) from the National Botanic Gardens in Glasnevin, in particular section “**3.6 Dealing with propagations**”:
 
> Historically when a propagation was undertaken in the National Botanic Gardens, the original Accession Number was used. To all intents and purposes this is still quite useful, however, the following plants were all propagated in 1998, they are all only 2 years old, but would have carried these numbers for the rest of their lives.
> 1886.009462 _Ilex aquifolium_ 'Smithiana'
> 1926.004182 _Salix fargesii_
> 1962.009425 _Ilex_ × _altaclerensis_ 'Hodginsii'

for cases similar to the above three plants they seem to think that adding a **Lineage number** next to the Accession number offers a way to keep both parts of information.

further in the same section you read: 
> A _Pittosporum bicolor_ in front of the 1st year lecture hall was propagated on the 5th March 1998, however, two treatments were involved. The former (1998.1667) was put in the side frame of the old propagation house, while the latter (1998.1669) was put on the misting bench. The **1998.1669** label was returned to the herbarium as 'failed to strike', while the **1998.1667** plants number three. The value in issuing two numbers is that we have now learned that placing _P. bicolor_ cuttings under mist is of no apparent benefit. Likewise having different numbers when propagations are done at different times of the year or with different treatments (hormone powder, bottom heat etc.) will eventually make the database a source of much useful information on propagation techniques. Likewise certain individual shrubs or trees can be very stubborn at striking. If necessary grafting or tissue culture techniques could be applied to material you are anxious to propagate

Now Ghini already offers the possibility to associate propagations to plants and to document their treatments and results, but it does not facilitate the task of associating a new accession number to a successful propagation.

**Comment by fruit-github** [comment]
As a mere collector/gardener, not a botanist or biologist, I have wondered about this and run through the propagation section only to find no way of identifying my new plant - so yes this would be a usefull addition I think.

**Comment by RoDuth** [comment]
@mfrasca What about this approach?  Is this what your looking for?

Create a propagation in the "Propagations" tab of a plant like I have already done here:

![screenshotprop2](https://cloud.githubusercontent.com/assets/15710055/22360956/e5b89b62-e4a0-11e6-8cff-63a4e3855838.png)


Then create a new accession and selecting "Garden Propagation" as the source. Enter the plant number and a list of propagations will appear for you to select from.:

![screenshotpropogation](https://cloud.githubusercontent.com/assets/15710055/22360797/2a786acc-e49f-11e6-986b-91f131a117c7.png)

Is that what your talking about?  I was starting to use this a bit at MRBG, was very hand!  Would put it up there as one of my all time favourite features!

Then searching I would use either: 
`accession where source.plant_propagation_id != 0`
or something like this
`accession where source.plant_propagation.plant.accession.code = 2016.0001`


If I was going to suggest a feature that would be nice to have it would be to make the "Parent Plant" a hyperlink...  Just a thought.

![screenshotprop3](https://cloud.githubusercontent.com/assets/15710055/22361055/bb7a51fa-e4a1-11e6-9867-79cdf4ad04bd.png)

**Comment by fruit-github** [comment]
That is what I was looking for but it is obviously not quite as simple as I imagined it might be.

Your example is propagation from seed - so obviously a new Accession
The few propagations I have done here recently have been leaf cuttings, so clones and I assume would be classified under the same Accession - perhaps I am wrong and they should be new Accessions

I will have a play later and see what happens

**Comment by RoDuth** [comment]
@fruit-github I would only consider something to be part of the same accession if it came from the same _batch_ of cuttings (all the same treatments, taken at the same time, from the same plant, etc. etc. all things identical) so any new cuttings would make new accessions.  There was no particular reason that I chose to use seeds in my example, it works the same for either type (seed, cutting, other).  Its simple enough to trace the lineage if you ever need to.

**Comment by fruit-github** [comment]
You are correct of course and I am confusing terms used. 
Accession relates to the event of introduction to a collection and not the specimen introduced - I think ;)

**Comment by mfrasca** [comment]
Seems that @RoDuth and the writer of the article agree on practice, although not terms used. **LIneage number**, mentioned in the article, is the **Parent Plant** suggested by @RoDuth .
(by the way: this feature looks as if added for the UBCBG, I will look in the commit logs.)
there are still a couple of issues I think:
1) users (@fruit-github as an example) don't find this feature. We need to document it better.
2) I obviously agree on the hyperlink idea. We need to add it.
3) when you choose **Garden propagation**, the software could already build the list of plants with propagations, so you don't need remember, guess, risk mistakes. — with autocompletion.

**Comment by mfrasca** [comment]
to @fruit-github I would suggest reading [the pdf I linked when opening the issue](http://www.botanicgardens.ie/educ/accnosho.pdf). you will find it interesting. it is based on practice and our software does not contradict  their hints.
for example paragraph 3.1, page 3:

>1. Each Accession Number identifies one or a group of plants that:
>  * are of the same taxon
>  * are of the same propagule type (or treatment)
>  * were received from the same source
>  * were received at the same time.

**Comment by fruit-github** [comment]
I missed that link at the start of the thread, yes, it is very interesting and clarifies a number of points, in my mind at least, thanks. 
Working through the @RoDuth illustrated example is good - and should enable me to keep track of my small home collection.

A big reason why I have been confused is that I am not familiar with some of the terminology used, I am sure those working in botanical gardens and similar won't have that problem. That's true of all specialist fields and caertainly not a complaint
I am not sure that ghini's documentation is the right place to educate those like me but links such as the one above would be great IMO

**Comment by mfrasca** [comment]
@fruit-github if I may ask... do you think you could fork this project, review @RoDuth illustrated example, find a nice spot in the documentation where it fits, edit the documentation accordingly, then generate a pull request for me? I will be glad to review and accept. Don't worry about "I'm not qualified": as a user, you qualify perfectly according to me, and don't worry about botanic correctness, we have enough people who will review and correct. The starting point is what we miss!
The docs follow a stiff structured that does not help finding "the nice spot" I'm talking about. You can either write a new rst document next to what we already have (we must then add it in `index.rst`, possibly between `tagging` and `report`, or before `tagging`), or put your text in `tagging.rst`, as a new chapter. It will automatically appear in the overview.

**Comment by mfrasca** [comment]
I have time, I'll make a start on the conversion of this issue into documentation.

**Comment by mfrasca** [comment]
related but possible different issue: you create an accession, you select a propagation as its source, you would expect the software to be able to determine the species for you. this is not the case. you need to explicitly insert the species in the accession's General tab.
I wonder and I did not test: the software lets you change identification of any accessions. will it navigate all the propagation links? what do users expect?

**Comment by mfrasca** [comment]
what I've just described in the docs (only return those plants with propagations) was indeed marked as `TODO`, but not published in an issue. the code is in source.py:838, function `plant_get_completions`

**Comment by mfrasca** [comment]
when presenting the list of propagations (Propagation trials) associated to a parent Plant: 
* should we still include those which were already associated to an Accession? 
* or should we list them and disable them? 
* or not list them at all?

**Comment by mfrasca** [comment]
mistake in the interface: 
* you activate one row (click on its checkbox),
* select but not activate a different row (click on its text),
* activate a third row.
the window will now present an inconsistent situation:
![screenshot from 2017-05-18 14-48-26](https://cloud.githubusercontent.com/assets/122869/26220662/1b0ff078-3bd9-11e7-99f8-0841ca237e90.png)

**Comment by mfrasca** [comment]
![screenshot from 2017-05-18 15-28-31](https://cloud.githubusercontent.com/assets/122869/26222184/ac2d111c-3bde-11e7-8d26-75ca2535c201.png)
the link (Plant→Propagation→Accession) (the two strings in the above picture »used in 2007.28.009« and »used in 2007.28.010«) is **not** a hyperlink, and to convert it to one is comparatively complicated, as we need splitting elements in the interface. we only want the 'accession' part of the propagation summary to be a hyperlink, not the whole line.

**Comment by mfrasca** [comment]
should show the `used in %s` text only if the accession referring to the propagation is already in the database, as it is now, it's confusing.

**Comment by mfrasca** [comment]
even though... maybe in the editor better show a text like "used here".

**Comment by mfrasca** [comment]
funny enough, the widget with the code for the parent plant is called `parent_plant_eventbox` and indeed it is already a `GtkEventBox`, it's just not yet connected to the event.

**Comment by mfrasca** [comment]
now I need to let the software do what the documentation says:

> Using the data from the Propagation trial, Ghini completes some of the fields in the General tab: Taxon name, Type of material, and possibly Provenance. You will be able to edit these fields, but please note that the software will not prevent introducing conceptual inconsistencies in your database.

**Comment by mfrasca** [comment]
I think we can close this one. please open a new issue in case you think I've missed something. be specific! 😃
