### ISSUE TITLE
we miss the definition of finalised propagation

### ISSUE THREAD

**Issue by seraliam** [Ghini/ghini.desktop#186]
Propagación
Al finalizar la propagación, continua mostrándose en las plantas, la información de la propagación finalizada.
Mostrar las opciones de editar la propagación cuando no se ha obtenido el 100%, de semillas germinadas u otro tipo de propagación.
Si luego de el tiempo estimado no se ha producido la germinación o la otras pruebas de propagación no dieron resultados, permitir colocar la cantidad que se obtuvo resultados favorable (semillas germinadas u otro prueba) y no continuar mostrándolo en la planta.

**Comment by mfrasca** [comment]
![screenshot from 2017-06-06 17-46-09](https://user-images.githubusercontent.com/122869/26855360-1084b2c2-4ae0-11e7-9861-00defa81f353.png)
here we see the number of seeds in the trial and the day we started the trial.
after a while, seeds will start germinating, this date we fill in in 'Fecha de germinación',
after a while, we will give up waiting for more seeds to germinate, this date we fill in in 'Fecha plantado',

* I think that the 'fecha plantado' does not belong here if you want to interpret it differently, that is as date in which you have planted the resulting seedlings in the garden. that is something you write in the resulting Accession. so if we rename 'fecha plantado' into 'fecha finalizado' we don't need to change the database structure.

I'm not convinced we should inhibit editing after the 'fecha finalizado' has been filled in. after all, it's your data, you can decide what to do about it. what if someone filled it in by mistake?

we were also discussing a different but closely related issue: if the propagation has been accessed, you can specify the "quantity received". 
- as long as this is less than the resulting quantity in the propagation, it is fair to let the user still access material from the propagation. 
- as soon as the accessed material equals the propagated result, you can inhibit accessing the propagation again.
- the above would mean that propagation trials without resulting quantity will not be available for accessing them
- you can always edit the propagation and increment the resulting quantity, so you can access the propagation again.
- it would be nice to have an "add accession" button in the propagation editor.
- selecting the propagation from the accession editor source tab now fills in taxon and type of material. it could just as well fill in the initial quantity to the current still unaccessed quantity from this propagation.

**Comment by mfrasca** [comment]
@RoDuth do you want to have a look at this? I have defined the concept "accessible propagation", which is a propagation that has produced material and this material has not yet been completely accessioned in the collection.
we are in the task of looking for sources for a new accession. the user has decided it's an internal propagation, a Garden Propagation. so we start looking at plants:

- plant without propagations. fine, stop here, next plant.
- plant has propagations that have not yet produced anything. fine, stop here, next plant.
- plant has propagations and these have produced new material, we have to look deeper:
we examine one propagation at a time
- propagated material has not yet been accessed at all, fine, this material can be accessioned. offer we use up all the accessible_quantity.
- propagated material has been accessioned, but not completely. offer the difference.
- propagated material has been accessioned completely (an accession refers to it and its initial qualtity equals the quantity of the propagation). this defines a closed propagation, same as not there any more, next propagation. you're always obviously free to edit the propagation and increment the quantity, then the propagation will appear next time you try to insert a new accession.

the advantage of all this complication? 
- foremost: a shorter list in the completion, user won't be bothered with historical propagations.
- marginally: less typing on user side when accessioning a propagation.

I would like to hear your impression
