### ISSUE TITLE
contact editor lets user request insertion of conflicting contact

### ISSUE THREAD

**Issue by seraliam** [Ghini/ghini.desktop#187]
Al seleccionar la ventana para agregar un contacto no me permite ingresar los contactos. 
Aparece Error aplicando los cambios. 
 (sqlite3.IntegrityError) UNIQUE constraint failed: source_detail.name [SQL: u'INSERT INTO source_detail (name, description, source_type, _created, _last_updated) VALUES (?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)'] [parameters: (u'Santa F\xe9', u'Parque Nacional Santa F\xe9.', u'Unknown')]

**Comment by mfrasca** [comment]
![screenshot from 2017-06-08 16-55-17](https://user-images.githubusercontent.com/122869/26952502-593a088c-4c6b-11e7-93b8-0cd3e7d8c90a.png)
![screenshot from 2017-06-08 16-55-32](https://user-images.githubusercontent.com/122869/26952501-5938dd90-4c6b-11e7-8533-3c55cc0b0f2e.png)
![screenshot from 2017-06-08 16-55-35](https://user-images.githubusercontent.com/122869/26952500-59283fb2-4c6b-11e7-868b-7068ca2dda78.png)
at the second step, Ghini should show a pink 'name' field (name exists already) and a disabled OK button

**Comment by mfrasca** [comment]
`SourceDetail` (which we also call `Contact`) is such a small thing, we can rewrite it following the documented and testable pattern.
- remove the `SourceDetailEditorView` which is superfluous according to our documentation,
- replace the `SourceDetailEditor` with just a single function as we've done elsewhere,
- rewrite the `SourceDetailPresenter`,
- write a couple of tests,
- and at least solve the current issue.
