### ISSUE TITLE
allow user unset intended location

### ISSUE THREAD

**Issue by mfrasca** [Ghini/ghini.desktop#19]
@RoDuth #15 
> If we decide not to plant something we either just delete the accession or remove one of the intended locations (this isn't possible right now, seems you can enter them but once they are there they are locked in and you can change them but not remove them). 

(if in 1.1 we organize the intended locations as a list, then you can add or remove elements.)

**Comment by mfrasca** [comment]
I'm considering this:
![untitled](https://cloud.githubusercontent.com/assets/122869/12531301/f3f805f0-c1c4-11e5-925d-3cd047411bcf.png)
the two buttons would allow you to:
- edit the list (would look similar to the checklist in the batch taxonomic check) 
- add a new location (opening the location editor)

**Comment by RoDuth** [comment]
Looks really good!  Any chance of the option to add dates and numbers?  I'm thinking that if a line in the list could look like this (where 01.01.01 is a location code): `01.01.01; 12; 24/01/2016` or even `Loc: 01.01.01; Num: 12; Date: 24/01/2016` it would be great!  Would completely satisfy my needs from #15 
>
I figure that if you can put an accession with zero quantity and no plants it would solve a lot of the polluted data concerns (it's easy enough to have an "accession where quantity_recvd!=0" part to the query). But to do this I would need "intended location", "intended planting date" and "intended quantity" kind of like a list with 3 fields or table with 3 columns.   ....(slightly edited from the original comment for clarity)

(can even see a day where there is a `+` button, with tool tip "add to the collection", on the right hand side of the list and you highlight a line from the list click `+` and it deletes the line and opens the plant editor with the 3 fields of data filed in from the list.  You just have to fill in any further details and click OK.  Wouldn't that be an amazing, quick work flow!)

**Comment by mfrasca** [comment]
I can add the fields you mention to the database, so 1.1 is ready for it.
the interaction you describe would be possible, yes.

**Comment by mfrasca** [comment]
this is good enough according to me, at least as far as 1.1.1 is concerned (I want to release a first frozen 1.1 database structure).
your suggestion, I'm considering it, but it should go in a later issue, not blocking in milestone 1.1.1

**Comment by RoDuth** [comment]
Seems good, would love the extra functionality I mention but can wait for now.  I notice that the info pane seems display the old method still?
