### ISSUE TITLE
Nombre vernácular

### ISSUE THREAD

**Issue by seraliam** [Ghini/ghini.desktop#192]
En el Nombre Vernáculo esta escrito "Nmbres Vernáculos"

**Comment by mfrasca** [comment]
esto está en po/es.po, y lo he cambiado hace poco.
ahora están, por traducir o traducidos, los textos:

    po/es.po:478:msgid "<b>Vernacular Names</b>"
    po/es.po:3192:msgid "Vernacular Names"
    po/es.po:3196:msgid "Vernacular names"

which we could clean up anyway.

**Comment by mfrasca** [comment]
forgot to close the issue... 🍭 🇵🇦 🇨🇴 🇪🇨 🇻🇪 🍭
