### ISSUE TITLE
fix ABCD export

### ISSUE THREAD

**Issue by mfrasca** [Ghini/ghini.desktop#2]
I've reviewed most field names and by doing so obviously things broke.
now it's just 9 failing tests which sounds not so scary as when I run the test suite the first time, with less than 10 passing tests.
the failing/erroring tests fall in two categories. one is the ABCD export.
and @RoDuth , do you think you could contribute a real life export against which to test Ghini/Bauble?

side comment, the main difference now is that all epithets are called `epithet`, instead of `family` as string field of family but as object link of genus, or `genus` as string field of genus but as object link of species. calling an epithet `epithet` was already so in the JSON import/export and will probably make the step shorter, if we ever decide to tackle mfrasca/bauble.classic#9.

**Comment by RoDuth** [comment]
@mfrasca regarding an ABCD export (or any export)...  I have been thinking about this and I do see one problem, you may think me a little over cautious here but there are a lot of individual peoples full names and addresses, memorial plantings and specific location data that points to private properties in the real world data I have and I don't feel like I have permission to give it all up.  But also, I reckon it would be a good idea to put a SQLite test environment together for new users? One that gets included in the installation files. It's one of the most common requests I have had with new users, some data to play with.

So I have 2 options:
*  I could spend sometime going through it and deleting data or altering the details for anything that I can see a problem with.  Fake names etc. I'll make sure I have enough things in there that are truly representative of the way we use things but it could end up messy... 

OR
*  Put a mock database together in SQLite.  Just 30-50 plantings from 20-30 accessions in 8 locations, something like that.  A few notes, tags, pictures, vouchers and other things like that.  And others could add a few examples also.  Build a really good test environment for the new user that may grow over the years...

I like the sound of the second option, I might put a bit of time aside for it in the next few days if you like. 

It just occurred to me, you can't currently **import** via ABCD anyway can you?

p.s. got Ghini up and running :smile: but no luck connecting to my current DB, it keeps coming back with errors (not that I expected it to be flawless or anything).  And a JSON export/import only gets me a handful of accessions and 2 plants.  Will there be script or something to update the database from v1.0 to v1.1 (like the `bauble-upgrade-0.9-to-1.0.py` in the scripts folder) or is it going to be via a manual export/import only?  I worry how much data could get lost!  (history etc.) Have never had much luck with the import/export of a whole database :disappointed:

**Comment by mfrasca** [comment]
just a very brief note: check http://bauble.github.io/resources/cuchubo.db
ghini-1.0 should work flawlessly, if it does not please open an issue.
ghini-1.1 is not expected to work yet, if it does please open a bottle.

**Comment by mfrasca** [comment]
upgrading the database, I'm afraid it will be through a script. it will be faster for the user and you will not miss anything (history in particular, I do not plan exporting history in JSON).
I am not aware of any code doing the ABCD import and please do open an issue about the fact you do not see it in the user interface. the JSON import is currently (1.0) the only non-destructive import you have at hand. it does not do a perfect job and please open issues for all failures you encounter, with attached json data. the csv import is the fastest we have and it will destroy all that was previously in the database. it is just perfect for the upgrade task. I think it does not even work when you import from one backend to the other, I think I tried this two years ago and I ended exporting the data from the SQL interface, edit the INSERT instructions more or less by hand, then import in the other backend.

about the cuchubo database. the land belongs to the heirs of Carlos Pontón (should be like 20 people, many of whom at no less than 1000km from the garden), although old Néstor Pontón might successfully fight for exclusive ownership, if he cared doing so. the collection probably already belongs to Néstor. @smbantjes and myself are the ones who did the job of digitalizing it so I guess we are allowed to share the data. we also have several pictures associated to something like 20+ plants, but we never put that in the database. at the time we did it, the software did not handle pictures associated to plants. I might use the new URL link capability, and put the pictures somewhere online, like in http://ghini.github.io/resources/cuchubo/ and I think I should open an issue myself, but you can do so if you like the idea.

**Comment by mfrasca** [comment]
oh, but I should close this issue because it does not fail any more and it does not show an interactive window on failure.

**Comment by RoDuth** [comment]
You know me, I cant help but play with the latest!!  And I did say I didn't expect it to be flawless!  Sorry most probably shouldn't tinker :smile: 

Cant say I'm too concerned about import/export but when I next run into a reason to use it and have any issues I'll look at what went wrong and put up the issue.  A script sounds good, was only an out of interest question.

The cuchubo DB is a handy item to have, never knew it was available.  I will say that it appears to still not be a really good example of some of the things you can do with Bauble.  Its looks like a lot of our older collection that I am adding now where I don't have much data, lots of single plant accessions etc..  Problem I have with giving up our data isn't so much that I care who owns it as who is in it.  There are just too many names of people in there, and with some potentially sensitive data. (addresses, business names, lat/longs of private properties etc.)

**Comment by mfrasca** [comment]
(you will not be able to use the **same** database for both 1.1 and 1.0) (and I am considering splitting the configuration too, so you can run the two versions parallel to each other) (and I wonder if we should not do something similar to when you install python2.7 next to 2.6 and 3.x and you want them all not to mess up with the others but you want a default one)

**Comment by mfrasca** [comment]
you can fake information in the cuchubo database, like donors, but preferably you do so for plants in a location that is clearly a fake location, not one of the 1.a etc that are real sections in the garden, nor some new section if we ever find the time to go back to Mompox and explore the rest of the garden. so call them f.1 (fake-1) etc.
then you fork the site, update the file, open a pull request. you know how it works! :)

**Comment by mfrasca** [comment]
... and if you do so, you may ask your helping people to complete it with extra documentation, like a tutorial!
