### ISSUE TITLE
publish the JBQ guide as part of rtfd

### ISSUE THREAD

**Issue by mfrasca** [Ghini/ghini.desktop#216]
Users at the JBQ (@denadenisse, ) have a short internal guide, written in Spanish of course, which we are going to include into [our documentation](http://ghini.rtfd.io).
The process to do this will be a bit convoluted, because we start now from a Spanish translation, which we have to split in sections and will go into a `po` file, and it is relative to an English text which we do not have yet, and once we have this English text, our `doc/runme.sh` script will produce the `po` file into which we will put the Spanish translation.
As said, a bit convoluted.

**Comment by mfrasca** [comment]
part of it, it's generic information and I would remove it from the short guide and just use it to review the current generic information.
most of it, it's a list of recipies, which is very good, we've been missing it. it was my plan "user stories", which never became anything.

**Comment by mfrasca** [comment]
we have included the initial documentation, but it's written in foreigners' Spanish, so the steps are:
- add the new documentation page to our site (in whatever language)
- add any new documentation in English (🤣my own Italian English🤣 )
- prepare the translation strings
- translate them into Spanish Spanish using weblate
- finally replace the original strings with their English translation

in order not to wait and wait and wait, I'm going to misuse one of the translation languages, one of the sleeping languages, for parking the final step (GermanSpanish to Italian English) somewhere safe.

**Comment by mfrasca** [comment]
Hola Denisse, he incluido tu texto, 

- hay una parte que he vuelto a integrar pues sino no se entiende qué es la "suggested practice". La dejaste descrita en manera incompleta. Bueno, miramos como hacerlo de manera que se entienda y que el JBQ se quede conforme.
- No me pusiste el archivo `Plant origin description.png`. Oye, si es una descripción, no sería mejor ponerla en un texto que en un PGN?
- Algo que yo no entiendo leyendo tu texto: en **practica**, qué es lo que hace en JBQ con las notas de las accesiones? La única información para que veo la necesidad de una nota es la "razón", tanto para donaciones cuanto para decomisadas, pero no me parece que falte la categoría para estas fuentes. Lo que llamas "Donor" es el nombre de un contacto/fuente de tipo "individual"; similarmente para "Enterprise": el nombre de un contacto/fuente de tipo "commercial".

Estoy completamente de acuerdo que cuando hayas seleccionado el tipo de contacto, no se entiende en el software porque todos se parecen a expedición. por eso que abrimos la issue #235.
 
Acuérdate que para las compras el JBQ ya utiliza notas con categoría 'factura' y texto de la nota el número de la factura.

En el ejemplo de decomisar, para evitar problemas de ensuciar el nombre de algún vivero que realmente existe, utilicé "Riina y Mancuso". Y si alguien se molesta, cambiamos a "Acme".

**Comment by mfrasca** [comment]
:bell: still needing review 🔔

**Comment by denadenisse** [comment]
Respondiendo a tus observaciones

1.- Creo que esto ya lo discutimos. Me explicaste mejor esta parte, quedo claro que se trata de una medida para identificar géneros cuando estamos hablando de otras familias que no son solo Orchidaceae.

2.- En cuanto a la fotografía, la he adjuntado en pictures como recomendaste, todavía no esta habilitada? que debo hacer?

3.- Con respecto a las notas, también lo hemos hablado ya. Recuerdas? hemos quedado en colocar una nota, clasificando por categoria: donación, factura, decomiso. En el caso de no saber la fecha exacta si no solo el año, colocar una fecha ficticia que podría ser: 01/01/2011  para las plantas que ingresaron en una fecha incógnita pero en el año 2011.

4.- No me disgusta la idea de enunciar el nombre con uno ficticio, aunque, hay que considerar que si el MAE encuentra una planta que fue decomisada a ACME, no estará conforme puesto que se realizan oficios legales de decomiso en conjunto con esta entidad. Lo que podría sugerir es colocar el número de oficio asociado   proporcionado por el MAE a cada decomiso, de esta forma, se podría asociar un origen discreto del decomiso.

5.- Con respecto al issue #235 quedo claro que los campos de fuente solo aplican para expediciones.

**Comment by mfrasca** [comment]
la campanita 🔔 es porque todavía no he recibido comentarios de los usuarios directos.

**Comment by mfrasca** [comment]
lo dejo abierto porque falta algo que puedo hacer yo mismo, o @seraliam, o sea describir el protocolo de inventario que, con la ayuda de @JoHegg y @alissmorales elaboramos y experimentamos en el INV3.
