### ISSUE TITLE
Automatically loading of photos by location and RegExp

### ISSUE THREAD

**Issue by ngdias** [Ghini/ghini.desktop#225]
The software could automatically load photos in a predefined folder (without having to add filenames tom to the DB) and read either filename (using a standard format) or metadata to pick the photos that correspond to the current accession number. This way the user could add a large number of photos just by editing the photo file. This would also help keep the DB small.

**Comment by mfrasca** [comment]
I see two way to interpret your hint:
- batch import pictures
- implicitly associate pictures
implicit association I would probably not want to do, because I have the idea the database should be self-contained. changing a setting (where to find pics) can break the association in once case (you don't find them any more), but in the case of implicit association it would make them disappear tout-court, as if they had never existed.

**Comment by mfrasca** [comment]
in the meanwhile I've had to solve a similar problem for the JBQ, and I've written a small script meant for importing pictures in the database.
the situation there was:
- accession codes look like 6 digits, no separator
- our database only has one plant per accession
- we have a list of pictures names
- each picture name starts with the 6 digits accession name
- we may have more than one picture per plant
- the rest of the picture name makes the name unique
- there might be a picture for a plant or even an accession not yet in the database
- we want some feedback on what is going on
- we associate an unidentified accession to the fictive species _Zzz_ sp.

the script is `scripts/importpictures.py`

**Comment by mfrasca** [comment]
what we could do in a GUI...
- assuming the user put all pictures in the expected location
- assuming it's very clear which accession and which plant is mentioned in the picture name
- loop over all pictures, separating the cases:
  - picture is already mentioned in database
  - picture is not mentioned in database
    - there is only one plant to which the picture can be associated
      fine, just lay the association and put picture in list 1
    - there is more than one plant in the accession, and it's not obvious which one is in the picture
      nope, do nothing and put the picture in list 2
    - there is no plant in the accession, or there is no accession
      put the picture in list 3
- review list 1 as "done, fine"
- review list 2 as "can't do much about it"
- review list 3 as "select which ones I'm going to add to the database"

**Comment by mfrasca** [comment]
@ngdias , would the above be useful to you ?
you wish to suggest corrections or comments ?

**Comment by mfrasca** [comment]
most user interaction is in place. you can select the image containing directory, you can review the data that are going to be imported, you can edit accession numbers if you think so.
there is no interaction with the database yet.
following steps:
- let user select or create the default location,
- implement data import step (from `box_review` to `box_log`),
- write import log in `log_buffer`,
- commit or rollback as actions to Ok or Cancel.

**Comment by mfrasca** [comment]
I consider this finished, any possible mistake in the code, please open a new issue.
