### ISSUE TITLE
insert same or similar information for group of objects

### ISSUE THREAD

**Issue by denadenisse** [Ghini/ghini.desktop#247]
Producto de expediciones existen grupos numeros de plantas que comparten la misma información en cuanto fecha, localidad, coordenadas geográficas e información en cuanto a  permisos de investigación y movilización proporcionados por el Ministerio del Ambiente. Me parece que si hay un grupo numeroso de plantas que comparten información entre ellas, ingresar esta información una por una, es demoroso.
Mediante el uso de tags podriamos filtrar las accesiones que comparten información para importarla en grupo?

**Comment by mfrasca** [comment]
así como lo escribes aquí, se trata de accesiones nuevas, y que quieres insertar información fundamentalmente compartida entre un objecto y el siguiente.
en esta forma, para objectos nuevos, ya hay una issue muy parecida.
ahora busco.
#91, originariamente mfrasca/bauble.classic#4

**Comment by denadenisse** [comment]
Estimado Mario, la pregunta del caso 247 si habla de accesiones recién ingresadas, no accesiones por ingresar, es por eso que hablo de filtrar las accesiones con TAGS, para asociar la información de la tabla que adjunté, que por cierto, especifiqué verbalmente que columnas necesitaba, aparententemente no quedo claro. El título del issue lo dice: ´´Asociación información para un grupo de accesiones´´. Creo que es innecesario realizar este tipo de comentarios por esta vía.

**Comment by mfrasca** [comment]
ok, it is now clear to me. this is just the same as #248.
