### ISSUE TITLE
importar detalles de objectos ya en la base de datos

### ISSUE THREAD

**Issue by denadenisse** [Ghini/ghini.desktop#248]
Como anexo al issue #247, si clasifico las accesiones ya presentes en la base y quiero asociar informacion extra para todo el grupo, como se podria hacer esto.

**Comment by mfrasca** [comment]
Esto lo haría ampliando el script  [/scripts/csv2json.py](https://github.com/Ghini/ghini.desktop/blob/ghini-1.0-dev/scripts/csv2json.py). 
Si es para una sola vez, se hace fácil, el problema es hacerlo genérico y configurable.
I'm not sure if this would need any work, after we solve #127.

**Comment by mfrasca** [comment]
me pasas también la correspondencia entre en número de colecta del botánico (LB/MJ) y en número de accesión en la colección del JBQ? sin esa no se hace nada.

**Comment by mfrasca** [comment]
otra cosa: las dos columnas de las coordenadas tienen tres tipos de datos diferentes. Northing/Easting, Latitud/Longitud(decimal) y Latitud/Longitud(dms). no es un problema importar del uno o del otro, o de todos, pero se me hace complicado importar de una columna cuyo contenido no esté bien definido.

**Comment by mfrasca** [comment]
bueno, al final de las 26 columnas parece que sólo te interesan tres, o sea que todo el tiempo empleado ayer para estudiar la forma de los datos que me pasaste ... bueno ya está, que le vamos a hacer.
Las tres columnas relevantes son para asociar el N° De Autorización de Investigación y el N° autorización de movilización al nombre de la Localidad.
proyectando sobre las tres columnas y quitando las repeticiones, las 520 filas se vuelven 23. hay tres casos en que a una misma Localidad corresponden dos números de autorización de movilización diferentes. Importar estos casos necesita más información.

en práctica, es lo equivalente de las #247, pero para objetos ya presentes en la base de datos.

creo que la descripción inicial no deje entender el punto a qué está interesada, y que la discusión sólo sirvió para aclararlo, mejor cerrar el issue y abrir uno nuevo más informado, sin tanto ruido.
