### ISSUE TITLE
expand contact model

### ISSUE THREAD

**Issue by mfrasca** [Ghini/ghini.desktop#25]
> (c) contacts could include a flag for receipt of seed list and email address to use for the seed list.

from @tmyersdn Bauble/bauble.classic#277

**Comment by mfrasca** [comment]
@tmyersdn, could you spend a couple more words about the above?

email address, that's clear, but **_a flag for receipt of seed list_**, how would you use this?

**Comment by mfrasca** [comment]
actually, "how would you use that", the same question applies to **_email address_**, why would you need a separate field when you have a multiline description field?
just asking, and trying to avoid work that is not necessary.

**Comment by tmyersdn** [comment]
Hi Mario, I will reply to the questions above under new issues,

Can you help me understand: what is a "contact", is this a source from the accessions table? Or is it something else?

**Comment by mfrasca** [comment]
in terms of the Bauble/Ghini database structure, a "Contact" is not a `Source`, it's a `SourceDetail`.
in ITF2 terms, it's a `Donor`

**Comment by tmyersdn** [comment]
from a user viewpoint, is this seen as the "source details" window that opens when you click on "new" source in the accessions source tab?

**Comment by mfrasca** [comment]
yes, that is it. you can get to the same window by following Insert→Contact from the main menu.

**Comment by tmyersdn** [comment]
ah, okay, I am on Bauble 1.0.55, that option is not there.  Yes, I would like to move to Ghini, I will do that as soon as time permits this week.

**Comment by mfrasca** [comment]
I think I will commit changes into `bauble-1.0` as well, and anyhow, 1.0.56 is not out yet so you would not find it in `ghini-1.0` either.

**Comment by tmyersdn** [comment]
just a note on ITF2: Donor.  - I would feel pretty uncomfortable including email addresses or peoples names in Donor for export to BGCI.

**Comment by mfrasca** [comment]
I see your concern; what about a **private** flag so you can inform the reporting script not to include the donor?
we already have this in accessions, not that I know of any reporting script acknowledging it.

```python
    # ITF2 - E6 - Donor
    name = Column(Unicode(75), unique=True)
    # extra description, not included in E6
    description = Column(UnicodeText)
    # ITF2 - E5 - Donor Type Flag
    source_type = Column(types.Enum(values=[i[0] for i in source_type_values],
                                    translations=dict(source_type_values)),
                         default=None)
```

**Comment by tmyersdn** [comment]
That sounds good, but note, this is probably a minor concern for BGCI reports. At present BGCI just asks for taxonomy fields not all the extended data fields like donor.

But it probably makes sense to include a private flag just to because privacy is an issue.

Also, I think having an separate email field will mean that email addresses are kept out of the "donor" description field.
