### ISSUE TITLE
Elaboración etiquetas seriales con ID no existentes en la base de datos

### ISSUE THREAD

**Issue by denadenisse** [Ghini/ghini.desktop#256]
En el caso de salidas de campo, hablando con Lucho se ha concluido que para no perder el tiempo asignando un ID de colecta que luego deba ser asociado a un número de accesión JBQ, sería bueno asignar los números definitivos desde el comienzo, para lo cual deberíamos poder imprimir un serial de número para que Lucho les asigne desde el inicio, y evitar este paso intermedio de búsqueda y enlace de los códigos. O bien, en el caso de necesitar un rango secuencial de etiquetas que aún no existen en la base de datos (para reetiquetado por ejemplo, como lo hemos estado haciendo), o por ejemplo, etiquetas nuevas que Miguel Ángel quiere colocar en los bonsai. Como se realiza el comando dentro de ghini para producir estas etiquetas seriadas?

**Comment by mfrasca** [comment]
la descripción de arriba es la idea que planteé a Lucho hace unos días y me parece que la presentes correctamente.

falta la distinción entre dos tareas diferentes:
1) la creación física de las etiquetas, no sé si Lucho querrá viajar con las 1000 etiquetas en su morral,
2) la creación de las accesiones "vacías" en la base de datos.

para la primera, he añadido la opción "[modelo mako paramétrico](./220)", y los dos formularios para [código de barra](https://github.com/Ghini/ghini.desktop/blob/ghini-1.0-dev/bauble/plugins/report/mako/templates/accession-label.svg) y para [código QR](https://github.com/Ghini/ghini.desktop/blob/ghini-1.0-dev/bauble/plugins/report/mako/templates/accession-label-qr.svg) que ya utilizamos (creo que hayan sido las etiquetas 25801-25872). No se te olvide, al utilizarlos, de especificar el color negro, sino no salen bien.

para la segunda, lo más rápido es crear un archivo JSON para las accesiones "vacías" e importarlo.
voy a escribirlo, aunque seguramente eres capaz de hacerlo tú misma.

**Comment by mfrasca** [comment]
```bash
#!/bin/bash

echo -n '['
for i in $(seq $1 $2)
do
  [ $i -ne $1 ] && echo -n " "
  echo -n $(printf '{"object": "accession", "species": "Zzz sp", "code": "%06d"}' $i)
  [ $i -lt $2 ] && echo ,
done
echo ']'
```
