### ISSUE TITLE
Creación contraseñas diferentes usuarios 

### ISSUE THREAD

**Issue by denadenisse** [Ghini/ghini.desktop#257]
He intentado crear los diferentes ususarios que incluyan la opción de edición y lectura pero no borrado (no-delete), y la que solo es de lectura (lector), pero no sé como asignarle una contraseña especifica a cada tipo de usuario.

**Comment by mfrasca** [comment]
Supongo estés hablando de usuarios PostgreSQL. Por favor: más detalles de lo que has hecho, cómo lo has hecho, cuáles usuarios has creado.
Estoy pensando escribir un pequeño script `bash` para simplificarle la tarea cada vez que entre un nuevo usuario, aunque temporal, en le jardín.

**Comment by mfrasca** [comment]
1) make sure you can use password autentication (https://stackoverflow.com/questions/18664074),
2) make sure your `bauble` user has the `createrole` privilege,
possibly edit your `~/.pgpass` file, to simplify the next step,
3) login to the `bauble` database as `bauble` user, then
4) for each user `<user>` with password `<pw>` that you want to create, do the following:
`create role <user> with login encrypted password '<pw>';`
`grant all privileges on all tables in schema public to <user>;`

as said... voy a escribir un pequeño script que haga el punto 4, pero los puntos 1 y 2 hay que asegurarse estén en orden, sino la cosa no marcha.

**Comment by mfrasca** [comment]
tienes razones para no utilizar el tools→users ?
![image](https://user-images.githubusercontent.com/122869/29947642-5c549bf8-8e70-11e7-98dc-bbd72b5cc21e.png)
hace tiempo que no lo he revisado, y no está incluido en las pruebas unitarias "continuous integration", así que quizás no funcione correctamente.

**Comment by mfrasca** [comment]
aclaramos que lo que aquí llamas "crear los diferentes usuarios" en efecto es la creación de las conexiones.
por supuesto no puedes asignar contraseñas a los usuarios en esta ocasión pues las conexiones se refieren a los usuarios ya definidos en la base datos.
los usuarios de base datos los defines a través de la herramienta 'usuarios' o del script que acabo de poner en el repositorio.
no pudimos solucionar la cosa hoy pues se nos cayó la base datos y ojalá la reparen antes de lunes próximo.
sin embargo la issue me parece referirse a una incorrecta comprensión de la estructura de los datos. la traducción al castellano todavía está parcialmente en la versión producida en automático. me puedes indicar cual parte no está clara, y abrir otra issue, o quizás mejorar tú la traducción?
