### ISSUE TITLE
Importación fotos no tomadas con ODK collector

### ISSUE THREAD

**Issue by denadenisse** [Ghini/ghini.desktop#258]
Hemos tomado fotos con la cámara del Lucho, de orquídeas por ejemplo del género Lepanthes, que son muy pequeñas y que necesitan del uso de un macro para poder registrar a la flor y características taxonómicas útiles. En este caso no estamos usando al ODK collector, como debemos proceder para la importación de las fotografías, cada foto tomada estaría etiquetada con el código de accesión de 6 dígitos. De igual forma cual es la forma correcta de proceder para que estas fotografías queden registradas en el servidor?

**Comment by mfrasca** [comment]
has intentado añadir una foto a la planta? si todo está funcionando correctamente, si tienes bien configurado el enlace ![image](https://user-images.githubusercontent.com/122869/29942268-e34dd7d4-8e5a-11e7-9fb5-c4a8e22beda1.png), debería el programa mismo ocuparse de copiar la foto en la carpeta 'pictures root'.
me permito de cerrar el issue. si no funciona como descrito arriba, por favor vuelve a abrir, pero me añades el `.bauble.log`.
