### ISSUE TITLE
ghini.pocket_error visualizacion data accesion

### ISSUE THREAD

**Issue by denadenisse** [Ghini/ghini.desktop#274]
Mario,
El aplicativo ghini.pocket es muy util, y ha mejorado mucho en este corto periodo de desarrollo. Sin embargo, en algunos dispositivos moviles que usan el aplicativo, al momento de realizar una busqueda, se observa un error de lectura en el campo de familia, donde no se visualiza el nombre como tal de la familia sino la descripcion del contenido de JAVA. 
Adjunto una captura de pantalla.

![img-20170915-wa0002](https://user-images.githubusercontent.com/29124586/30491892-61c50d80-9a04-11e7-9d19-432151044ed7.jpg)

**Comment by mfrasca** [comment]
puede ser conectado con el idioma, no sé, es algo que pasa en esta parte del código:
```java
 if(dismissDate != null) dismissDate = dismissDate.substring(0, 16);
 noOfPics = String.valueOf(resultSet.getInt(9));
```

**Comment by mfrasca** [comment]
This issue was moved to Ghini/ghini.pocket#13
