### ISSUE TITLE
dead ABCD export menu item

### ISSUE THREAD

**Issue by RoDuth** [Ghini/ghini.desktop#290]
After selecting a file to export to nothing happens.

Was broken by 273fd1f
https://github.com/Ghini/ghini.desktop/blob/0063fcea6cdb80829b8492b06fa0df3ada2c6760/bauble/plugins/abcd/__init__.py#L343
should have read 
```
if filename is None:
    return
```

**Comment by mfrasca** [comment]
I see, as said, it was not very readable to me... and I simplified making a mistake.

**Comment by RoDuth** [comment]
Thanks.  :+1:
