### ISSUE TITLE
follow one naming standard when naming variables

### ISSUE THREAD

**Issue by mfrasca** [Ghini/ghini.desktop#293]
### Expected behaviour
single or at least consistent naming style

### Actual behaviour
many variables in the new `scripts/build-multiuser.nsi` are all UPPERCASE (not all of them), a new file in the `scripts` directory starts with uppercase.

this produces an inconsistent structure, where the reader may be confused and wonder if the difference is significant. if it is not, please change back to all lowercase.

this snippet shows the situation:
```
!define VERSION "1.0.75" ; :bump
!define src_dir "..\dist"
!define PRODUCT_NAME "ghini.desktop"
Outfile "${PRODUCT_NAME}-${VERSION}-setup.exe"
!define PROGEXE "ghini.exe"
!define COMPANY_NAME ""
!define license_file "LICENSE"
!define readme "README.rst"
!define startmenu "$SMPROGRAMS\${PRODUCT_NAME}"
!define UNINSTALL_FILENAME "uninstall.exe"
```
it looks confusing, some definitions are "SHOUTING", some are quiet.

same for `Add_to_PATH.vbs`: it's the only file in the whole directory starting with a capital letter. traditionally, first upper case letter was meant to pull a file to the top of the listing. now less relevant, but still better follow a single naming style.

it's not a bug, really, though it may bug readers.

**Comment by RoDuth** [comment]
see #294 

and comment [here](https://github.com/Ghini/ghini.desktop/pull/286#issuecomment-336448829)

**Comment by RoDuth** [comment]
OK, I take that comment back, seems it will compile either way.  Seems the convention is to use all capitals (a github search `extension:nsi !define` shows almost all are all capitals.). Changing the 4 variables I had as lowercase to all caps.

**Comment by mfrasca** [comment]
please follow one style on all similar files.
you added a new `.nsi` file, next to an existing one.
try to keep things uniform across the two files.

**Comment by mfrasca** [comment]
closing dangling issues
