### ISSUE TITLE
py2exe vs pyinstaller

### ISSUE THREAD

**Issue by RoDuth** [Ghini/ghini.desktop#296]
To make a windows installer we freeze the code.  Currently that is done with py2exe.  Is this the best tool for the job?  Would pyinstaller (or cx_freeze, etc.) be a better solution?  It works on more OSes and there is some suggestion that people have been able to compile for windows in linux using Wine.

pyinstaller benefits:

- multi-platform
- Easy install: `pip install pyinstaller` (py2exe is via a windows only installer)
- Better documentation
- Seems to be in more active use
- Is on [github!](https://github.com/pyinstaller/pyinstaller/) (vs py2exe still on [sourceforge](https://sourceforge.net/projects/py2exe/))
- May have a better solution to the MS Visual C++ DLLs (need to check this re: license concerns)

**Comment by mfrasca** [comment]
I have no opinion on this. see what fits you best, document its usage, and file pull requests.

**Comment by mfrasca** [comment]
I guess we're happy with py2exe, at least on Python2.7.
the new ghini.desktop-3.1 line runs on Python3 and uses Gtk3, I would open separate issues if any arises.
