### ISSUE TITLE
tag deletion

### ISSUE THREAD

**Issue by tmyersdn** [Ghini/ghini.desktop#30]
from overview of tags #27 

Do you think it would be useful to be able to close and remove tags in bulk. Ie when a tag is no longer useful to delete it from all instances?  To save you the work of going through record by record and deleting it.

Sorry if this is already possible and I have not noticed?

**Comment by mfrasca** [comment]
you want to `delete` all tags (or a large quantity of tags)
or you want to `untag` all that is tagged by a specific tag?
end of the day for me, will look into it tomorrow.

**Comment by tmyersdn** [comment]
specific tag. But I think you already answered my question, can select tagged records by query, then ctrl-A to select all, ctrl-T to toggle tags off.
But what happens if a record has more than one tag, does ctrl-T remove all tags?

**Comment by mfrasca** [comment]
@tmyersdn , any question about the behaviour of the software is best answered by the software itself.
that is: try it and see if you like it or how you would like it better.

**Comment by mfrasca** [comment]
by the way, @tmyersdn, you are using Bauble-1.0 and which patch (last number)?
do you want to move to ghini-1.0, or would you prefer I keep maintaining bauble-1.0?
I am about to release 1.0.56 (ghini/bauble)
I do not plan opening and maintaining bauble-1.1 myself.

**Comment by mfrasca** [comment]
Ctrl-T opens the Tags window. the Tags window lets you set/unset any tag (one-by-one) on all objects (all at the same time) in the selection.

**Comment by mfrasca** [comment]
with the new Ctrl-Shift-Y (#28), you would:
- pull down the tags menu
- select a tag (it would become the active tag)
- select all objects in the tag
- hit Ctrl-Shift-Y

a briefly flashing window would inform you that the tag has been removed from all objects in the selection.
