### ISSUE TITLE
Add version timestamp to the About window

### ISSUE THREAD

**Issue by szlajozs** [Ghini/ghini.desktop#300]
I think that adding an additional line containing the version timestamp text between the version line with bold larger font size and the Copyright line with small font size would be useful.

Why?
For example let's see my particular case:
I'm a user very new to Ghini so I don't know the exact behaviour of the app yet. I got a notification email from Github about the availability of a new version, but this notification didn't contain any info about the exact release number, only "[Ghini/ghini.desktop] publish to 1.0 (#298)". According to the documentation I expected a notice about the new version at program start, but there was nothing. As I don't know the behaviour of the app, one possible explanation that came into my mind: "what if that there was an automatic upgrade to the new version, let's check the About window!" The only useful info I knew from the About window was that my installed version is 1.0.75. As the notification email from github doesn't contain the precise release number (or I didn't find it), I don't know whether my installed version of 1.0.75 is up to date or not. I only remember that I installed Ghini some time in November and the Ghini notification is dated 4th Dec. So this is why the version timestamp would be a very useful info on the "About" screen. (At least in this particular case ...)

**Comment by mfrasca** [comment]
I'm looking into it now. There's a few things that complicate the solution and I'm afraid that the solutions I see are just as error prone as the current practice. Let's see...

-------------------------------------

Imagine we put the timestamp in `bauble/version.py`

when do we do that? 
- not at the same time when running `scripts/bump.py`, that's not the moment we publish the new version, that's just any time between the previous publication and the current one.
- best at the time of publishing
- possibly during the very process of publishing, included in `scripts/publish.sh`.

trouble is: how do we guarantee that the person publishing remembers they should use `scripts/publish.sh`? we are back to the initial problem.

----------------------------------------------------

what about we don't report the **publication** timestamp, but the timestamp of the **installation**?

or we could retrieve the publication timestamp during installation (not sure if possible).

----------------------------------------------------

I'm lowering the priority. 😉

**Comment by mfrasca** [comment]
at the moment, our About window is realized using the `gtk.AboutDialog` function. this creates a very standardized, recognizable object where you can set the following properties (in **bold** the ones we're using):

**name**, program_name, **version**, **copyright**, comments, **license**, wrap_license, **website**, website_label, authors, documenters, artists, translator_credits, **logo**, logo_icon_name.

I will have a look at the 'comments' field, how it gets formatted, and my idea is to include installation date and publication date (or the text: "make sure you have an internet connection"). (this would be collected at program startup, at the same time as when we're querying github for the latest release.)
