### ISSUE TITLE
hybrid char on Windows is x instead of ×

### ISSUE THREAD

**Issue by mfrasca** [Ghini/ghini.desktop#301]
@RoDuth ­— can you have a look at this, is this still the case?

        if sys.platform == 'win32':
            # TODO: for some reason using the cross as the hybrid
            # character doesn't work on windows
            Species.hybrid_char = 'x'

**Comment by RoDuth** [comment]
Never noticed this but then don't have a lot of hybrids of this nature in the records (and our label reports output a multiplication sign for the hybrid flag).
From a VERY quick look I don't think its needed.  I deleted these lines in a Win7 VM and ran a py2exe build (py2exe has some caused me some weird issues with unicode chars in the past) and all seemed to work fine.
I see this was committed in 2009 so it may be relevant for earlier version of windows (Win7 is the earliest version of windows I have easy access to at the moment) but considering that the multiplications character is used in other areas of ghini (notably when adding a species hybrid with the '*' trick) and hasn't yet lead to anyone saying they are having issues I'd say it _should_ be fine to delete these lines.

**Comment by mfrasca** [comment]
please confirm that »all seemed to work fine« means that you:
- deleted those two lines overriding '×' with 'x'
- reinstalled the software
- created a hybrid species
- perform a search that contains the hybrid species in the results
- see the '×' character in the results view
- select it in the results
- see the '×' character in the infobox — right hand side.
if you can confirm this, just say "yes, confirmed" 😉 

if it only means that you think the above would be the case, please say "no, not confirmed"
thank you so much, and have a nice change of year.

**Comment by RoDuth** [comment]
That was what was meant by

>  I deleted these lines in a Win7 VM and ran a py2exe build ... and all seemed to work fine.

What I didn't check is any other versions of windows its fair to assume that anything past 7 should be fine but possibly not XP or even Vista.
