### ISSUE TITLE
tags given by query

### ISSUE THREAD

**Issue by tmyersdn** [Ghini/ghini.desktop#31]
from overview of tags #27 

Is it possible to create and run a query, and apply a tag to all the results of the query?

Once again, sorry if this is already possible!

**Comment by mfrasca** [comment]
this is what happens when you hit Ctrl-T
you run a search, click on one of the rows in the search results, click Ctrl-A to select all rows, click Ctrl-T to tag them, the tagging window opens and the rest goes by itself I think.
