### ISSUE TITLE
"Acquisition" to group multiple accessions acquired at once from a single source

### ISSUE THREAD

**Issue by mfrasca** [Ghini/ghini.desktop#320]
_From @sehrgut on October 26, 2015 13:41_

I'm not sure how useful this would be for the real target audience for bauble, but I'm using it to manage my garden and collection. It would be useful to me to be able to create an "Acquisition" object which grouped multiple Accessions (such as a large purchase from a vendor, or a number of cuttings gifted by another collector).

It would also be useful to be able to track purchase price for both Acquisitions and Accessions. At present, that must be stored in Notes, where it's difficult to report on. (That may be useful as a separate issue?)

_Copied from original issue: Bauble/bauble.classic#159_

**Comment by mfrasca** [comment]
_From @RoDuth on November 14, 2015 1:19_

I have asimilar issue with when the accessions all come from a field trip to collect specimens from the wild.  If I collect 15 ferns for our native fern collection from the one 20m stretch of river bank then they all share the same geographic info (locale, region, lat/long or GPS datum, accuracy, altitude, habitat) but I have to type it in for each and every accession.  There must be a way to speed this up in this scenario. 

Maybe a copy/paste button for source details?  So that you can click copy the first time you enter it and then paste it in for all the others accessions.  Or an "extract source details from accession: foo" button?  Which, when you click it, it grabs the data and auto fills.  This would be great in other scenarios also, like when we do cover more area with some of our collection trips.   All details are the same except slight differences in the lat/long of each accession, after grabbing or pasting the data in you could still edit it to capture the slight differences.

I know its not quite the same issue but it is related.  Currently I create a new source for each collection trip with a unique name (including the date in the name).  This allows me to search by that source name and find everything collected on that trip.  This is may be one way you could deal with the original issue.  If you create a new source for each Acquisition then you could sort by the one purchase.  Gets a bit messy I guess.  As it does with my collection trips as individual sources.  If there was an Acquisitions object then I could just have a few collection trip types as Sources and then more specific info in the Acquisitions to link all items from a specific date.  Still doesn't solve my issue of having slight variations in the lat/long data for individual accessions though.

Sorry that took me so long to explain!

**Comment by mfrasca** [comment]
I think what @RoDuth writes is related to #51 , something like "unless edited here: inherit from previously edited object". and I wonder whether `Tag` would help @sehrgut .

**Comment by mfrasca** [comment]
in case you do not need the `source's ID`, you could use that field to solve the issue.
like in:
`accession where source.source_detail.name = 'Vivero Acme' and source.sources_code = '#150-3'`

if the above does not solve the issue, please reopen! thanks.

for the price and new fields, see new issue #263

**Comment by mfrasca** [comment]
@sehrgut , when you write »stored in Notes, where it's difficult to report on«, can you elaborate that? why do you call it difficult?

**Comment by mfrasca** [comment]
_From @sehrgut on January 16, 2018 17:37_

Since Notes is a free text field, it has no semantics. This means that a report on "all plants from a given acquisition event" would need to make use of some notational convention WITHIN the notes field, that everyone editing the data would have to know and use consistently.

If, instead, there was an "Acquisition" object (or even field) which could model an acquisition event (e.g. "Purchase from <nursery> on <date>" or "Donation from collection of <donor>" or something like that, it would be trivial to discover all accessions from a given acquisition.

**Comment by mfrasca** [comment]
That (weak semantics) is indeed what we do now for plant coordinates, and for series of values. For the time being, that is to give us time to understand what usage is going to be made of this information, we're instructing users on how to insert coordinates, and data series (arrays and dictionaries), that are only available in reports and exports.  Same goes for the CITES and IUCN fields, which seem to have never been actively used.  Same again goes for URL of pictures.

But you see, there's such a wide range of requirements on extra fields to our objects, I cannot introduce a database change every time we add one, we need more flexibility. A change in database structure means data migration, a main show stopper for institutions in using a program, as far as my experience goes.

It's the "or something like that" that blocks me. Do you think you could help me take a more informed decision, let me understand what fields do you need in an acquisition event: show me how you're using this data, in queries, in reports, and how you're inserting it now in the database.

I am already considering adding typed data to the database (implies a change in the DB structure) (and I'm afraid I forgot to open an issue for this), but I want to do it well and for once, so we don't need to redo it later again.  My initial thought was typed data in the form of native types (and geography), but if I look at your request, you're talking of defining your own structured type to add as an atomic note... That would be interesting, but introduces many more difficulties, for example when implementing queries, how to define the type definition, should we associate a note category to its type?  so all notes of that category share the same type, forcibly?

Maybe not necessary to open a new issue, we can stay here, but we have to rename it once we agree on how to enhance the software.

**Comment by mfrasca** [comment]
_From @sehrgut on January 16, 2018 21:0_

Well, I'm not running an institutional collection, so my personal use case is:

> I acquired these plants from the same source, I'd like an easy way to find all the plants I got from the same source over time.

So a new object type is simply the most obvious solution I saw to that problem. The data I personally would store in an acquisition event would be things like GPS coordinates for wild collection, contact information for nurseries, and URLs to invoices stored in Dropbox.

However, for me, just having an atomic name to tie all accessions in an acquisition together, even if I had to put that metadata in a freeform field, would still be useful.

**Comment by mfrasca** [comment]
still, from what you write, I don't see how the current Notes implementation isn't enough. can you give a **very** concrete example? not explaining, but showing, maybe in tabular form, what you would like to put in the database?

**Comment by mfrasca** [comment]
sorry, I had forgotten I promised we would handle issues on Ghini/ghini.desktop, not here on Bauble/bauble.classic.  I'm going to migrate the issue there.

**Comment by mfrasca** [comment]
> The data I personally would store in an acquisition event would be things like GPS coordinates for wild collection, contact information for nurseries, and URLs to invoices stored in Dropbox.

> Since Notes is a free text field, it has no semantics. This means that a report on "all plants from a given acquisition event" would need to make use of some notational convention WITHIN the notes field, that everyone editing the data would have to know and use consistently.

you see, a report has to be programmed anyway, so there's little difference, from the programmer's point of view, if the data is in a single Tag with Notes, or in different Notes each with a specific category, or in a well defined class with the correctly named and typed fields.  the main difference is that in the last case you have guarantees about the data fields, while in case Tag with Notes and collection of categorised Notes you need to test consistency while reporting.

but the difficulties in writing the report are the same.

@sehrgut : I'm insisting in getting to see a couple of concrete examples (how your report would look like in practice) because this would help me lay down and fine tune with your help the requirements for this possible new class.

by the way: Tags can't have Notes, that's also something for ghini-1.1.

**Comment by mfrasca** [comment]
all the fields in this section:
![image](https://user-images.githubusercontent.com/122869/38677039-a8394f02-3e22-11e8-992e-a8b7c0d4b6fc.png)
are specific to the expedition, and we are requesting users to fill them over and over again for each accession in the same expedition.
the other section:
![image](https://user-images.githubusercontent.com/122869/38677087-d3efb7f8-3e22-11e8-8984-a117f0018237.png)
is indeed specific to the accession.

**Comment by mfrasca** [comment]
I have a quick and dirty test, just to keep things together, published with 1.0.81:
you add notes to objects, same category, same text, you select an object with that note, you double click on the note, the software writes for you a query that will group all objects of that same type, with a note with same category, same text.
you can see it at work in the last minutes of this video: https://youtu.be/HhvelKic5Rs

**Comment by mfrasca** [comment]
I think that [this plan](https://github.com/Ghini/ghini.desktop/issues/339#issuecomment-385178072), sketched in #339, would solve this issue withing 1.0, and with much more flexibility.

**Comment by RoDuth** [comment]
> is indeed specific to the accession.

For us this would often not be true. We would often go to a small 10-20m stretch of a rain-forest river bank and collect 20 species (ferns etc.).  We'd record this as 1 lat/long with an accuracy that was wide enough to account for all specimens (say 30m).  We would tend to use this method with accuracy for most expeditions, sometimes making it as wide as 500m.  Habitat description would also be the same.
