### ISSUE TITLE
Updates on Mac and Windows

### ISSUE THREAD

**Issue by denadenisse** [Ghini/ghini.desktop#332]
We updated the database on Linux to the 1.0.80 version that is avaible now. 
 Unntil here, everything is just fine. But the link between the server and database in our others two equipments, one with osx and the other with Windows system are broken, ending with an empty database. (as shown on the photo).

![sin titulo](https://user-images.githubusercontent.com/29124586/38815985-bde5e8a2-415a-11e8-9b43-38e589b602fd.png)

First, we tried to update the app following your directions published on ghini.readthedocs. Any error message or problem was detected on the terminal window. I restarted both computers after ¨the update finished¨ but the actualization was not been done. We remained with the 1.0.67 in both osx an windows.

**Comment by mfrasca** [comment]
hola.  I've set the priority of this issue to "low" because I understand you can still run 1.0.67.  is it correct? or did you end up with a broken system, on both OSX and Windows?  if you attach the logs (just start each of the two systems, and close it, the log will be very short), I will be able to have a look at what is going on.  thank you.

**Comment by denadenisse** [comment]
Yes it is correct. THe 1.0.65 version is working, is just the link between the database and the server.
Sure, here they go.
on windows:

![sin titulo](https://user-images.githubusercontent.com/29124586/38941604-83937414-42f2-11e8-8513-b4228f5bbe94.png)

On osx:

![20180418_102507](https://user-images.githubusercontent.com/29124586/38942022-5cfb538e-42f3-11e8-9b78-4a047e557326.jpg)

It this what you needed?

**Comment by denadenisse** [comment]
Another thing to share with you. The update on Linux was made from scratch. It means that we reinstall Ghini because of hardware problems that this equipment presented last week. After start and linking the server with Ghini, both systems osx and windows stop working.

**Comment by mfrasca** [comment]
curious … and no, that's not exactly what I was asking (the logs), you sent me two screenshots.  You should be able to easily open the logs form the menu.
![image](https://user-images.githubusercontent.com/122869/38960457-376d7944-432a-11e8-8929-e7af3279b35c.png)

An other option would be to first try what you say you already did on Linux, I mean, you could re-run the devinstall script on both OSX (it uses the same script as Linux) and on Windows (that's devinstall.bat).

the other option, at least as far as the OSX machine is concerned, would be to open the tunnel we had prepared.  
but you wrote you did a complete new linux installation?  in that case, there's quite a bit of preparation work to do, I think you better ask for help so we can solve this easy and quick.

**Comment by denadenisse** [comment]
Hola Mario.
Ahora si, esto es lo que necesitas?Alguna idea de que fue lo que pasó?
Gracias
[bauble.log](https://github.com/Ghini/ghini.desktop/files/1939720/bauble.log)

**Comment by denadenisse** [comment]
Hola Mario.
Ahora si, esto es lo que necesitas?Alguna idea de que fue lo que pasó?
Gracias
[bauble.log](https://github.com/Ghini/ghini.desktop/files/1939947/bauble.log)

**Comment by mfrasca** [comment]
me has compartido el registro de la computadora en que tienes ghini.desktop 1.0.80 instalado y funcionante.  lo más que te puedo decir es que me parece bien.

**Comment by denadenisse** [comment]
Sip es lo mismo
Volví a correr la instalación del git y python. No se si cambia algo o no, pero la base esta vinculada ahora en el computador de Alice
Esta pantalla te dice algo?

![sin titulo](https://user-images.githubusercontent.com/29124586/39153180-fa367e92-470f-11e8-9ab3-85b4cfe93733.png)

**Comment by denadenisse** [comment]
Tranquilo, Aqui esta el detalle del mensaje
![sin titulo](https://user-images.githubusercontent.com/29124586/39153375-89597782-4710-11e8-8f12-3a85d2895688.png)
![sin titulo1](https://user-images.githubusercontent.com/29124586/39153382-8d38c128-4710-11e8-8970-695af7c91223.png)

**Comment by mfrasca** [comment]
si alcanzas enviarme el registro de la compu de Alicia, quizás pueda ver que está pasando ahí.
no entiendo la frase »la base esta vinculada ahora en el computador de Alice«

**Comment by mfrasca** [comment]
necesitas poner al día ghini en todas computadoras, no sólo en una.  usando la base datos con la 1.0.80 has añadido en la tabla 'bauble' unos valores que no son reconocidos por las versiones anteriores, en particular: `strq-initialized`.

**Comment by mfrasca** [comment]
para poner al día, te vuelvo a editar las instrucciones, las voy a hacer más uniformes con las de la instalación.

**Comment by denadenisse** [comment]
Al parecer Mario, el error es en la pantalla de inicio. Por favor cuentame si hay como arreglar esto.
Con respecto a tu pregunta, antes la base no mostraba ningún dato de planta, accesión o tag.
Ahora aparece así: 
![sin titulo](https://user-images.githubusercontent.com/29124586/39154138-dd7baf22-4712-11e8-99aa-3461ef1c3c19.png)

Y si uno da clic por ejemplo en generos, especies en uso: 
![sin titulo](https://user-images.githubusercontent.com/29124586/39154246-2dcabcca-4713-11e8-98f8-4188262e9b2e.png)

sale la informacion de la base del JBQ
![sin titulo](https://user-images.githubusercontent.com/29124586/39154271-450291c4-4713-11e8-9f03-6d488ab12707.png)

Como puedes ver, la pantalla de inicio sigue mostrando lo que te envié hace 7 dias, pero la información de nuestra base de datos si se encuentra.

Aqui esta Mario, lo que pides, es el mismo que el anterior:

[bauble.log](https://github.com/Ghini/ghini.desktop/files/1940111/bauble.log)

Por cierto, las actualizaciones del ghini no se estan efectuando. Voy a realizar nuevamente el procedimiento de actualización en el computador de Alice y te mando SCREENSHOTS. 

Denisse

**Comment by mfrasca** [comment]
no, no nada de screenshots, gracias. he visto el problema y es ese `stqr-initialized`, que no es producido por la 1.0.80 y no es reconocido por las versiones anteriores. necesitas poner al día, eso es.

**Comment by denadenisse** [comment]
Listo Mario, comprendido, la versión que poseemos tanto en osx como en windows no es la ultima, pero tras varios intentos no se actualiza.
Cuando hayas editado las instrucciones me dejas saber.
Muchas gracias, Que estes muy bien

Denisse

**Comment by mfrasca** [comment]
to make the answer more self-contained (las instrucciones se refieren a `devinstall.bat`, pero aplican también a `ghini-update.bat`):

descarga este archivo (click derecho y guardar como...):
https://raw.githubusercontent.com/Ghini/ghini.desktop/master/scripts/ghini-update.bat
![image](https://user-images.githubusercontent.com/122869/39154839-55dd1bd4-4715-11e8-8041-b8bd23e818da.png)

por favor, asegúrate que esté guardado como archivo bat y no como texto:
![image](https://user-images.githubusercontent.com/122869/39154847-5f0ca81e-4715-11e8-9cac-328b13955beb.png)

para correr el archivo, no necesitas abrir la pantalla de linea de comando:
![image](https://user-images.githubusercontent.com/122869/39154881-7f83bb0a-4715-11e8-8e17-5e8c2f0ac564.png)

por supuesto, si lo ejecutas de la linea de comando, tendrás la oportunidad de averiguar con más calma si todo marchó bien.

**Comment by denadenisse** [comment]
Mario,  como especifica en ghini.readthedocs, como puedes ver
![sin titulo](https://user-images.githubusercontent.com/29124586/39155293-055d9b64-4717-11e8-9fe0-eee42425d55a.png)
corre el script
![sin titulo](https://user-images.githubusercontent.com/29124586/39155397-87650e58-4717-11e8-9f3a-f80133e2eecf.png)

**Comment by mfrasca** [comment]
y entonces? lo instaló, no arranca? es lo mismo que viste la otra vez? no entiendo si todavía hay una pregunta.

**Comment by denadenisse** [comment]
Mario, no se actualiza el ghini, pese a que corre el script de actualización. Ese es el problema
![sin titulo](https://user-images.githubusercontent.com/29124586/39196030-c354ab5a-47a6-11e8-9ad1-9473d10a4bb4.png)

**Comment by mfrasca** [comment]
Los pantallazos que me sigues compartiendo dicen todos la misma cosa: estás activando ghini.desktop 1.0.65.  Esto lo entendí.  Falta entender la razón.  Quieres mirar si en el entorno virtual se han quedado instalaciones viejas de `bauble` y/o `ghini.desktop`?  No debería, pero no sé que más pensar.

"el entorno virtual" es la carpeta `C:\Users\JARDIN\.virtualenvs\ghide\` y la posición de las instalaciones de ghini.desktop y bauble relativa a esta raíz es `/lib/python2.7/site-packages/`.  esta carpeta está llena de archivos y carpetas que son necesarios al funcionamiento de ghini.desktop.  deberías tener úna sola cuyo nombre empieza por `ghini.desktop-1.0.` y termine en `.egg`, la más recién.  si tienes más, por favor toma nota de sus nombres, me lo comparte aquí y luego las borras.  lo mismo por favor haces para las carpetas con nombre que empiece por `bauble-1.0.`.

**Comment by mfrasca** [comment]
estoy instalando aquí la 1.0.65, para ver en que manera puedo mejorar la versión de desarrollo y solucionarte el problema del otro lado, dejando en Windows y en OSX esta más anciana pero que te funcione.  obviamente para interactuar con las últimas versiones de g.pocket, g.tour, y g.web deberás utilizar la versión de g.desktop más actualizada.

**Comment by mfrasca** [comment]
changed `stqr-initialized` to `stqv-initialized`.  it was not a wise choice, using as separator '_', an SQL wild-card.

**Comment by mfrasca** [comment]
we still do not know what is preventing your Windows and MacOSX from updating.
todavía no se sabe porque no puedes poner al día tus sistemas Windows y OSX.

**Comment by mfrasca** [comment]
@denadenisse, he estado buscando en el código y he encontrado y solucionado un par de potenciales fuentes de problemas.  la principal sospechosa era una puesta al día contribuida por otro jardín, necesaria para realizar instaladores windows ('setup.exe').  pero sin haber visto los registros de tus computadoras, no sé si he con eso solucionado tu problema, u otros y todavía estás bloqueada.
puedo suponer que se solucionó tu problema?  me cuentas, gracias.

**Comment by denadenisse** [comment]
OK. Te aviso cualquier novedad.

**Comment by mfrasca** [comment]
como te decía [un par de comentarios más arriba](https://github.com/Ghini/ghini.desktop/issues/332#issuecomment-384089790), tienes que bajar y ejecutar el nuevo [ghini-update.bat](https://raw.githubusercontent.com/Ghini/ghini.desktop/ghini-1.0-dev/scripts/ghini-update.bat).
este produce un archivo 'ghini-update.log', que me interesa ver.

**Comment by denadenisse** [comment]
Listo Mario, cuando haya avances te escribo. Por favor, si necesitas algo, escribelo a mi mail o contacto.

**Comment by mfrasca** [comment]
He cerrado la issue pues he tenido la oportunidad de entrar en una máquina Windows, instalar la 1.0.65 (o sea ponerme en tu situación), intentar la instalación de varias versiones intermedias entre 1.0.65 y 1.0.80, y seguir teniendo la 1.0.65, mientras ghini muestra el mensaje "Versión 1.0.82 a disposición en github".
La instalación de la 1.0.81 da inmediatamente mensaje de error y es evidentemente imposible.
La instalación de la última 1.0.82 soluciona la cosa, por eso digo, cierro la issue.

Para una próxima vez: si hay problemas en la puesta al día, por favor evita los pantallazos que dicen muy muy poco, y envíame los archivos de registro.  Ahora tienes uno más, se llama `ghini-update.log`.
Pudes comparar, para tu propio interés, la cantidad de información en ese archivo, con lo del pantallazo que me enviaste, que sólo muestra las últimas pocas lineas, de las muchas más en el archivo:
![sin titulo](https://user-images.githubusercontent.com/29124586/39155397-87650e58-4717-11e8-9f3a-f80133e2eecf.png)
