### ISSUE TITLE
Proposal for open letter to botanical gardens

### ISSUE THREAD

**Issue by comradekingu** [Ghini/ghini.desktop#346]
We should write a letter inviting botanical gardens to join ghini.
It would be useful if it had some options for what capacity volunteers are able to contribute in.
Some might, as I, need help translating the more specialist terms.

**Comment by mfrasca** [comment]
you're thinking of a modular letter?  something like what we already have as [welcome letter](https://github.com/Ghini/ghini.desktop/blob/ghini-1.0-dev/doc/welcome-letter.txt)?  
I have started collecting, cutting, glueing pieces of letters I've sent recently, and I've just added it as a document page, even if I'm not so sure we should include it in the documentation index.
if you want to [have a look](http://ghini.readthedocs.io/en/ghini-1.0-dev/open-invitation.html), you can already comment on what you miss.
but I'm quite sure I'm missing the point you're making in the last two sentences, if you want to elaborate, thank you!

**Comment by mfrasca** [comment]
hei, do you want to have a look, it's closing time here now.

**Comment by mfrasca** [comment]
oh, more stuff you can use to publicize ghini...
[CubaPanel84.pdf](https://github.com/Ghini/ghini.desktop/files/1985739/CubaPanel84.pdf)
translating it would be tricky, because you have to match the formatting.  if you want to attempt that, I can send you the odt.

**Comment by mfrasca** [comment]
you know something, I think we could have one page with several templates documents, that people can re-use if they think they want to contribute to Ghini.  we already have two (open-invitation, welcome-letter), but also the letter I sent to you when first contacting you, could also be included here, so it's more open to contributions, and available for native speakers who want to volunteer translations.

**Comment by comradekingu** [comment]
Any letter needs to be translated, so that must be first order or business.
Not even I read all of the letter I got. We need simple.
Get the minimum message across, then follow up. A foot in the door.

**Comment by mfrasca** [comment]
> We need simple

oh, then I think I should leave this to others.
in Italian, one would say: "prolisso" and "ipotassico".

**Comment by mfrasca** [comment]
@comradekingu , you happened to have time for this?  regards, MF

**Comment by comradekingu** [comment]
@mfrasca Sure, send it to me. I think I can reduce it down quite a bit.

**Comment by mfrasca** [comment]
"send it"? it's in the repository, [here](https://github.com/Ghini/ghini.desktop/blob/ghini-3.1-dev/doc/open-invitation.rst).  fork, edit, and propose.  or copy/paste, and send it to me by email, also good.  but the source is over there.  thank you!!!

**Comment by comradekingu** [comment]
@mfrasca Though not the actual content of the PDF, I had a go https://github.com/Ghini/ghini.desktop/pull/405
