### ISSUE TITLE
devinstall.bat fails if python3 is the default

### ISSUE THREAD

**Issue by mfrasca** [Ghini/ghini.desktop#374]
from #360; @RoDuth mentions »Can I also add that your devinstall.bat has issues that make it fail for unusual situations. The most glaring one that catches me out every time is the fact that it fails if you have python 3 setup as your default python. At least build_win.bat doesn't have that issue.«

**Comment by RoDuth** [comment]
easiest solution:
https://github.com/Ghini/ghini.desktop/blob/67f5f78a51ccfbf981caab58167e990a1106cf2d/scripts/devinstall.bat#L40-L41

should have absolute paths:
```
C:\Python27\Scripts\pip install virtualenv 2>NUL
C:\Python27\Scripts\virtualenv --system-site-packages .virtualenvs\ghide
```
Assumes a standard python 2.7 install as described in the docs of course.

My point was not about this specific situation so much as its hard to account for every possible situation on a users system in a simple batch file in windows (its no bash!).  There are so many variables at play in a windows system, particularly when it comes to python.  The py2exe/nsis installer solution avoids all those issues.

**Comment by mfrasca** [comment]
I don't think the above would be enough, for there's initially a check on being able to import gtk, in a style which isn't compatible with Python3.  anyhow, don't waste time on this one, this is really low priority.  I never met the issue myself.  if you happen to see this again, and you have to solve this on one system, please share the solution, so you will find it back yourself.

**Comment by RoDuth** [comment]
sorry, yes your right, basically all references to python, pip, virtualenv, etc., up to the point of activating the virtualenv should be absolute paths also (so same with line 6 and 12).  Last time I had to deal with it I just did everything manually rather than use the batch file.

**Comment by mfrasca** [comment]
actually, since (1) we now offer installation via setup.exe and since (2) python2 is in end-of-life, this issue is (1) already irrelevant, and (2) will become obsolete.
