### ISSUE TITLE
email for contact / source

### ISSUE THREAD

**Issue by tmyersdn** [Ghini/ghini.desktop#38]
from expand contact model #25 

"the same question applies to email address, why would you need a separate field when you have a multiline description field?  just asking, and trying to avoid work that is not necessary."

Answer: if you later want the function to create or hyperlink to create an email, then it would be useful to have email stored in a separate field.
Also, if you want to export a list of contacts and email addresses as a separate column, then it would also help to have email as a separate field.
Also again, email addresses change pretty often. I think it is a mistake to embed them in free text.

**Comment by mfrasca** [comment]
the field is now in the model, this issue is about adding the user interface.

**Comment by mfrasca** [comment]
since the fields are in the model, this issue is not any more blocking 1.1.1

**Comment by mfrasca** [comment]
for 3.1, I'm not going to add an email field, but associate notes to the object, then you can define a `<email>` note and your reports will be able to use it as if it were a object field.

**Comment by tmyersdn** [comment]
thanks @mfrasca, sounds like a good fix. Also, I guess I am a dinosaur - email is not the only communication option users might want. So, presumably, this use of notes would allow other communication methods as well.
