### ISSUE TITLE
installing on Linux, instruction on download devinstall.sh

### ISSUE THREAD

**Issue by aauioo** [Ghini/ghini.desktop#386]
A few days ago I updated Ghini, which went well. But I got reminded on a search I had before.
According to [read the docs](http://ghini.readthedocs.io/en/ghini-1.0-dev/installing.html#installing-on-gnu-linux) , You have to download the devinstall.sh script. Except for my browser (Firefox) does not give me the option to "download". I found out I could save the file using right click on devinstall.sh, a menu opens and I used "Save link as". I remember some frustration and I wish nobody has stress about installing Ghini. I would like to suggest to look at the instructions, or maybe add a download option.

**Comment by mfrasca** [comment]
maybe relevant: https://stackoverflow.com/questions/3802510/force-to-open-save-as-popup-open-at-text-link-click-for-pdf-in-html#comment86467391_21527905

**Comment by mfrasca** [comment]
Hi @aauioo , if you have time to review, thank you.
