### ISSUE TITLE
Twice the same button name in picture import dialog

### ISSUE THREAD

**Issue by aauioo** [Ghini/ghini.desktop#387]
I was trying to import an image and found this two buttons in the picture import dialog. Twice "Volgende".
I tried searching weblate for a reason but couldn't find an answer. Although they are named equal, they are functional as they should be "Back and Forward".
![schermafdruk op 2018-06-24 23-14-33](https://user-images.githubusercontent.com/39213505/41866294-fec02108-78af-11e8-9fa0-30b5852fe841.png)

**Comment by mfrasca** [comment]
this is curious, and seems specific to Dutch.
the two objects are defined as 

                  <object class="GtkButton" id="button_next">
                    <property name="label">gtk-media-next</property>
                    <property name="use_stock">True</property>
                  </object>
                  <object class="GtkButton" id="button_prev">
                    <property name="label">gtk-media-previous</property>
                    <property name="use_stock">True</property>
                  </object>

if I run ghini as `LANG=nl_NL.UTF8 ghini` I can see the same as you're showing here.  but if I run ghini in eg. English, or Arabic the two buttons show different:
![screenshot from 2018-06-25 14-12-58](https://user-images.githubusercontent.com/122869/41870573-0a358c40-7882-11e8-8f0f-1e46a1f6dfea.png)
![screenshot from 2018-06-25 14-13-50](https://user-images.githubusercontent.com/122869/41870590-10de2bc4-7882-11e8-9bad-604549454e46.png)

and by the way notice that the two buttons do not show the same in Dutch either:
![image](https://user-images.githubusercontent.com/122869/41870917-04bd0d1e-7883-11e8-876a-982650e9a2ee.png)
'previous' has arrows back (but says next) …
short, I would not know, I've looked online if it's been reported in gtk but no.

**Comment by aauioo** [comment]
I considered it to be a translation error, But could not find it. Maybe there is a second strange thing.
If I click on default location I get a list of the locations in the garden , but my feeling says it should be a folder in my computer. Or am I mistaken?
![schermafdruk op 2018-06-25 21-46-46](https://user-images.githubusercontent.com/39213505/41872367-ecad3c32-78c1-11e8-9952-573acb99fb9b.png)

**Comment by mfrasca** [comment]
> If I click on default location I get a list of the locations in the garden , but my feeling says it should be a folder in my computer. Or am I mistaken?

When you import a collection of pictures, you are translating it into data in your database.  
- Pictures will be placed in the `Pictures root` directory, as defined in the initial screen, 
- Text information from the picture file names will be parsed by ghini and used as species identification, and accession code.  
- You can help Ghini recognize your accession codes by entering your own `accession format` in the corresponding field.
- One plant per accession will be generated, and associated to the `default location`.

makes sense?

**Comment by aauioo** [comment]
Yes makes sense. Thank you.
