### ISSUE TITLE
flag for receipt of seed list

### ISSUE THREAD

**Issue by tmyersdn** [Ghini/ghini.desktop#39]
from expand contact model #25 

this flag would let the user mark the contacts that will receive particular emails - for example, if I want to manage a list of gardens to send an Index Seminum to every year.

Mario, I now think this issue would be better handled better by using "tags". As tags give you the flexibility to identify any number of "email groups".  But it still would be useful to have the contact store an email address as a stand alone field.
see `:tags` page to show overview of tags #27

**Comment by mfrasca** [comment]
I agree with using tags for this one and with the usefulness of a separate field for email #38.
