### ISSUE TITLE
is there a quick way to retrieve the IUCN status online

### ISSUE THREAD

**Issue by mfrasca** [Ghini/ghini.desktop#393]
I wish to enhance my collection, adding the IUCN status of every species in the collection.

### Actual behaviour
I have to look (online) in text form, and insert notes one by one

### Expected behaviour
something like the taxonomic batch review, or at least the-plant-list query

**Comment by mfrasca** [comment]
whether this is possible (allowed), or not, depends on the use that one makes of the information.  if all we do is to "use of the IUCN Red List Categories associated with each named taxonomic entity", then there is no restriction.  http://www.iucnredlist.org/info/terms-of-use

one possibility is that we would use this function:
http://apiv3.iucnredlist.org/api/v3/docs#species-citation-name, e.g.:
`http://apiv3.iucnredlist.org/api/v3/species/citation/Annona%20spraguei?token=<token>`

an other lighter option is to only download their lists at `http://apiv3.iucnredlist.org/api/v3/species/category/<category>?token=<token>` (these are the "no restriction associations"), and to include them in the distributed software.

I have requested a token for personal use, seems a human being is going to decide whether or not I may get a token.

**Comment by exiledonamarginalisland** [comment]
Chapter 3 says "However, IUCN warrants that you are free to view and query The IUCN Red List, and places no restrictions on use of the IUCN Red List Categories associated with each named taxonomic entity." which I believe would cover the specific point .... but I am no expert. Is it worth checking?

**Comment by mfrasca** [comment]
the best thing would be that they implemented an API as easy as "this function provides you with the IUCN Red List Categoriy associated with your named taxonomic entity", and that it requires no token.
I just gave them this feedback.
my point is, I would not want to distribute one of their tokens, while I would definitely like to redistribute the above described association RL-category←→named taxonomic entity.  so I guess we should download a complete list, matched with Botany, and we could include it in one of the ghini components.
not complex at all, just a matter of deciding what to do with the information, how to make it available to the user.
