### ISSUE TITLE
Report using Mako and example_species fails

### ISSUE THREAD

**Issue by kermesse** [Ghini/ghini.desktop#406]
### Expected behaviour
Generate report of species

### Actual behaviour
Formatting Error: 'NoneType' object has no attribute 'startswith'
See:
![image](https://user-images.githubusercontent.com/17342799/44404753-7ba1c980-a54f-11e8-9e18-a3c0fbfda09f.png)

```
Traceback (most recent call last):
  File "/home/kt529/.virtualenvs/ghide/local/lib/python2.7/site-packages/ghini.desktop-1.0.86-py2.7.egg/bauble/plugins/report/__init__.py", line 657, in start
    ok = formatter.format([row[0] for row in model], **settings)
  File "/home/kt529/.virtualenvs/ghide/local/lib/python2.7/site-packages/ghini.desktop-1.0.86-py2.7.egg/bauble/plugins/report/mako/__init__.py", line 429, in format
    report = template.render(values=values)
  File "/home/kt529/.virtualenvs/ghide/local/lib/python2.7/site-packages/Mako-0.9.1-py2.7.egg/mako/template.py", line 443, in render
    return runtime._render(self, self.callable_, args, data)
  File "/home/kt529/.virtualenvs/ghide/local/lib/python2.7/site-packages/Mako-0.9.1-py2.7.egg/mako/runtime.py", line 807, in _render
    **_kwargs_for_callable(callable_, data))
  File "/home/kt529/.virtualenvs/ghide/local/lib/python2.7/site-packages/Mako-0.9.1-py2.7.egg/mako/runtime.py", line 839, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/home/kt529/.virtualenvs/ghide/local/lib/python2.7/site-packages/Mako-0.9.1-py2.7.egg/mako/runtime.py", line 865, in _exec_template
    callable_(context, *args, **kwargs)
  File "_home_kt529__bauble_templates_mako_example_species_csv", line 62, in render_body
  File "/home/kt529/.virtualenvs/ghide/local/lib/python2.7/site-packages/ghini.desktop-1.0.86-py2.7.egg/bauble/db.py", line 574, in __getattr__
    elif n.category.startswith('{%s:' % name) and n.category.endswith('}'):
AttributeError: 'NoneType' object has no attribute 'startswith'
```

### Steps to reproduce the behaviour

Tools > Report > New 
Formatter: Mako
Template: example_species.csv

**Comment by mfrasca** [comment]
looks like you have entered a note, but not specified a category.
this is discouraged, but allowed.
the program should either be able to handle the situation, or prevent the user from inserting a note without a category, or correct the category to the empty string instead of leaving it `None`.
in the meanwhile, please edit your notes and give them a category.
thank you for reporting.

**Comment by kermesse** [comment]
Thank you. I have checked but there do not seem to be any notes. It may have escaped my attention because the database is quite large. Is there a way to look for all the items in the database that carry notes?

**Comment by mfrasca** [comment]
yes, but not in one shot.  as of ghini-3.1, there's 9 classes that define notes, namely  Location Accession Propagation Contact Plant Tag Species Genus Family.
in ghini-1.0, that's only 5:  Accession Plant Species Genus Family.
for each of these classes, you can query the database like this (in this case: Accession):
accession where notes!=Empty
(the capital letter `Empty` is relevant)

**Comment by mfrasca** [comment]
Hi again, let me know if this was the problem, otherwise I should examine it further, and I might need some of your data.

**Comment by kermesse** [comment]
Perfect it worked thank you! Using species where note!=Empty identified all the species where there were notes (typically the collector codes), and once a category was created and the notes were attributed to it, everything worked! Maybe it would be good to sort it though, maybe by making the category field compulsory or by giving the notes a generic default category? Thank you

**Comment by mfrasca** [comment]
> maybe by making the category field compulsory or by giving the notes a generic default category

yes, and I guess more the second you mention.
the issue is open and as of now it only has a workaround.
ciao, thank you.

**Comment by mfrasca** [comment]
just a note at the margin, next to your _**once a category was created**_.
note categories aren't objects, it's just a name that happens to have been mentioned.
you create a note, and you are hinted at the already existing categories.
in SQL, this happens with a `SELECT DISTINCT` query. it's very quick.
but you can ignore the hints, and type your preferred text, as a new category.
next time you create a note, the new category will appear in the pull down menu.
it's a good practice to keep a limited amount of categories.
and to consistently capitalize them, or they will be seen as different categories (Factura/factura)
as said, it's just a note at the margin.
