### ISSUE TITLE
Documentation: access to online documentation denied?

### ISSUE THREAD

**Issue by exiledinamarginalisland** [Ghini/ghini.desktop#416]
I would like to be able to access the documentation form ghini > help > content. When I click on it I see the following:
![image](https://user-images.githubusercontent.com/122869/44946047-e35edc80-adb9-11e8-8465-2bc6ecf685d1.png)

What am I doing wrong, and is there a fix?

**Comment by mfrasca** [comment]
it's a bug, a mismatch between client and server.  the server (read the docs) is configured to serve 1.0 documentation on http://ghini.readthedocs.io/en/ghini-1.0-dev/, while ghini is pointing you to http://ghini.readthedocs.io/en/latest/
I suppose I should fix it on the server.
thank you for pointing this out.

**Comment by mfrasca** [comment]
server-side: I enabled `latest` on readthedocs, and 
client-side: corrected the links in both 3.1 and 1.0.
