### ISSUE TITLE
Documentation: accessing documentation in offline mode

### ISSUE THREAD

**Issue by exiledinamarginalisland** [Ghini/ghini.desktop#417]
I would like to be able to access the documentation in offline mode when I am in areas where I have no connection. What do I have to do? Is there a way of installing ghini that includes the documentation?

**Comment by mfrasca** [comment]
please confirm that you have read a minimal tutorial about sphinx.
when you do a `devinstall.sh` installation, you have everything but the translated docs.
"everything" includes the documentation.
then producing the documentation locally is a matter of running the sphinx `Makefile`.

**Comment by mfrasca** [comment]
I think that the 'download it from readthedocs' is a viable answer.
you're always welcome with a different solution via a pull request.
ciao, grazie.

**Comment by exiledonamarginalisland** [comment]
Thank you for the explanation. I think the issue I am facing is that when I install sphinx in ghide, I get the following error:
![image](https://user-images.githubusercontent.com/10896183/45253545-6a3b2880-b369-11e8-8a5e-be0db7f8ba86.png)

Not sure what I am doing wrong. Any clue?

**Comment by mfrasca** [comment]
I still think that your (and any casual user's) best bet is to download the formatted docs from readthedocs.
if you want to help, try to remove the version specification in ghini pyparsing dependency and let me know.
thank you.
