### ISSUE TITLE
Launching version 1.0.87

### ISSUE THREAD

**Issue by exiledinamarginalisland** [Ghini/ghini.desktop#418]
I am trying to update to 1.0.87. I have tried both:

1) git pull
2) ghini -u

but I always end up with 1.0.86.

Am I doing something wrong?

PS: Kubuntu 18.04 LTS 64bit

**Comment by mfrasca** [comment]
I suppose you are on the `ghini-1.0` "production" line, which is the safe thing to do, so I guess you are doing nothing wrong, except expecting to move to 1.0.87: 1.0.87 is on the "bleeding edge".
if you want to move to the bleeding edge …, no, I don't think you want to move to the bleeding edge.
when I release 1.0.87, you will get the usual notification, and `ghini -u` will do its job.
the software is not telling you there is a new version, or is it? (in this case, please reopen)
