### ISSUE TITLE
Specify which sphinx version matches a ghini release

### ISSUE THREAD

**Issue by exiledonamarginalisland** [Ghini/ghini.desktop#423]
As a developer, I want to install sphinx in the same virtualenv as ghini, so that I can compile the docs locally.

### Expected/Actual behaviour
I would expect this to be described in the docs, but there is no mention of it.
I would install sphinx and run it, but I need to install it in the virtual env.
I would just run `pip install sphinx`, but this won't do because of the frozen `pyparsing` dependency in ghini.

#### Opinions and suggestions
maybe when we freeze the versions in `setup.py`, we should also mention which sphinx version goes with that specific ghini version?  if we leave this one floating to the latest one (currently 1.7.9), this is some time going to break compatibility with the distributed ghini-1.0.

### original text
This may relate to issue #417.

When one tries to pip install sphinx in ghide in order to make documentation, the following error appears:

![image](https://user-images.githubusercontent.com/10896183/45253636-c783a980-b36a-11e8-99cb-ae4600dc93a6.png)

Of course, this means sphinx is installed, but ghini 1.0.86 is broken. Then one can make html (to build offline html documentation). Once html documentation is built, to run ghini 1.0.86 you need to pip install pyparsing==2.0.1 in ghide, which of course breaks the sphinx installation.

**Comment by mfrasca** [comment]
please, provide the **full** sequence of what you do, as logs (text), not as screenshots (images).  for example, did you run ghini before reinstalling pyparsing?  did you get an error?  which one?

**Comment by mfrasca** [comment]
so, I removed the version requirement from `setup.py` and ran it again.  
now `setup.py` did the following:
```
Using /home/mario/.virtualenvs/ghide-1.0-dev/lib/python2.7/site-packages/python_dateutil-1.5-py2.7.egg
Searching for pyparsing==2.1.10
Best match: pyparsing 2.1.10
Removing pyparsing 2.0.1 from easy-install.pth file
Adding pyparsing 2.1.10 to easy-install.pth file
```

after this, I ran `pip install sphinx` in the same virtual environment, and I got `Running Sphinx v1.7.9`.  the installation mentioned pyparsing:
```
Requirement already satisfied: pyparsing>=2.0.2 in /usr/lib/python2.7/dist-packages (from packaging->sphinx) (2.1.10)
```

now both ghini-1.0.87 (unreleased) and sphinx-1.7.9 (latest) are in the same virtual environment and seem to work ok.

some of this should be mentioned in the developer's manual.

**Comment by mfrasca** [comment]
the latest sphinx version with compatible dependencies as ghini-1.0.86 is sphinx-1.6.7:
`pip install sphinx==1.6.7`

**Comment by mfrasca** [comment]
so, I don't know if there's a better way to do this, but now (that I added a `extras_require` section to the `setup.py` script) the following works:
- activate the virtual environment, 
- execute `easy_install ghini.desktop[docs]`

you now have the right sphinx version in your environment.  this is going to work starting 1.0.87.
