### ISSUE TITLE
Species addition confusion

### ISSUE THREAD

**Issue by cwyse** [Ghini/ghini.desktop#464]
As a user, I'm confused about how to enter highly cultivated 'species' that have no clear species name.

For example, the Hosta genus has many different cultivars, which have been hybridized with various species.  I believe that the correct nomenclature in this case is, e.g. Hosta 'Avocado'.  To obtain this name, in the species editor I use the genus Hosta and the cultivar epithet Avocado.  In my mind, this is also a hybrid, but if I check that box, I get Hosta x 'Avocado', which I don't think is right.  However, I want my labels to print correctly, so I leave the Hybrid box unchecked.

**Comment by mfrasca** [comment]
I should check and I will, but as of now I don't know for sure which is the right way to represent your case.  I would describe it as an unnamed species that is identified by its cultivar name.

what do you think of the following:
![image](https://user-images.githubusercontent.com/122869/77562918-9dcb9e00-6e8e-11ea-93b9-2c95f60b1758.png)

you get the above this way:
![image](https://user-images.githubusercontent.com/122869/77563364-2f3b1000-6e8f-11ea-80d2-2877c23767db.png)

-----------------------------------------

but I will check/ask what's the correct way to represent the case.  I think there's more than one interpretation.

**Comment by mfrasca** [comment]
according to https://www.ourhabitatgarden.org/plants/cultivars.html the current ghini behaviour is the correct one.  no need to add the intermediate 'sp' fictive epithet.  I can't find back the reference document, if you browse the closed issues, you will find it.  if you can find a place in the docs where you expect a link, we can add it.

**Comment by RoDuth** [comment]
@cwyse I do this a little differently.  I see the hybrid flag as being used to indicate the species name is a nothospecies hybrid name.  e.g.:
_Citrus_ × _limon_
_Abelia_ × _grandiflora_ 'Nana'
_Dendrobium_ × _delicatum_ (a natural hybrid)
(in which case you place _delicatum_ in the species field and check the hybrid box).

For cultivars (regardless of if you know they are interspecific hybrids or not) I just use the same as you suggest (enter a Genus, leave the hybrid flag unchecked and the species empty then add a c.v. in the infraspecific parts)  If you do know the hybrids parentage you can add it in the species field (but I rarely bother.)  This way you do get your:
_Hosta_ 'Avacado'

See: "Interspecific Hybrid Flag" [ITF2](https://github.com/tdwg/prior-standards/blob/master/itf2/102-525-1-RV.pdf) (p20)

**Comment by mfrasca** [comment]
Hi @RoDuth , thanks for the link to the 'reference document' I was missing.  looking at it now, I'm afraid it's not so particularly helpful here: both you and the 'reference document' aren't covering the case (or I am misreading both of you) for a hybrid without nothospecies epithet, but with cultivar name, which is what @cwyse focuses on.
let me mention that the space between the cross × and the following epithet should not be there, and is only due to limitations in the markup here on github.  the reference document is so old, that the `×` is replaced by a `x`.

**Comment by RoDuth** [comment]
I believe the space between the cross and epithet is optional. [see here](https://en.wikipedia.org/wiki/Hybrid_name#Forms_of_hybrid_names)

If @cwyse's intention is get his "labels to print correctly" then not using the hybrid flag is the correct way to do it in this example.  Assuming that a cultivar name such as _Hosta_ 'Avocado' is also a hybrid without information on the parentage is not something I would ever do or advocate.  It may just be a selection of a species without any hybridisation at all.  If you know that it is a hybrid then you can include the parentage in the species epithet if you like.  Aside from that just ticking a box to indicate you believe a cultivar is some form of hybrid is a little pointless.

ITF2 for better or worse is still one of the most common standard to which BGs refer.  If you want to take a look at ABCD and the other current TDWG standards (which were informed by ITF2 and HISPID), they take a similar approach to the hybrid flag anyway.

**Comment by cwyse** [comment]
My intent is to print labels correctly and to have the accession accurately described in the database.

@RoDuth: From your comment, it sounds like I'm doing it correctly.  Don't use the hybrid flag without knowing about specific hybridization.  You're right - the cultivar could just be a selection.  

That said, let's assume that I happen to know that Hosta 'Avocado' is a cross between two Hosta species.  In that instance, would the correct notation be Hosta x 'Avocado' ?  Would it indicate to the user that the parentage could be obtained via search?

**Comment by RoDuth** [comment]
@cwyse you could just add a note "considered a hybrid by such and such" or the like?  If you do know it is a hybrid then you should know the taxa it is a hybrid of.  If it is important to you, then include them in the species epithet (e.g. "capitata × minor" - if you type a '*' in the species epithet field it should add the cross symbol for you) in this example you will now get "_Hosta_ _capitata_ × _minor_ 'Avacado'".  

The following are technically correct (although made up):
_Hosta_ 'Avacado'
_Hosta_ _capitata_ × _minor_ 'Avacado'
_Hosta_ × _grandiflora_ 'Avacado'

_Hosta_ × 'Avacado'
is not:

This is my perspective on it, I work in a public botanic garden and if someone sees "_Hosta_ 'Avacado'" on a label they can buy it at the local nursery, talk to a gardener about it or look it up and find information on it etc., its sufficient information for the public.  If I include hybrid parentage one day I may need to untangle it.  Taxonomy is far from a binary art form, it is in constant flux, more akin to linguistics than mathematics or physics.  Consider this scenario:  All the var., subsp., f. of a species have been rejected by a recent review of the species and are no longer accepted, lumping them all back into the one specific taxon name (I had to deal with this scenario recently).  In this case an intraspecific hybrid cultivar is no longer a hybrid (e.g. using fictitious names _Hosta capitata_ var. _vitata_ × _capitata_ var. _gigantea_ 'Avocado' now becomes _Hosta capitata_ 'Avocado').  Same goes when several species are all reassigned to the one species name (e.g.  say _H. minor_ gets rolled into _H. capitata_. Hosta capitata × minor 'Avacado' now becomes Hosta capitata 'Avacado'.)  This happens way more often than most people realise and its hard to keep up with.  I see it multiple times each year.  "_Hosta_ 'Avacado'" is not wrong in any situation. "_Hosta_ (hybrid) 'Avacado'" (however you infer the hybrid) is wrong unless you KNOW it is a hybrid.  Are you sure that the parents are still considered unique taxa?  Mostly I prefer to avoid the pain.

That said if you really have the need to state that its a hybrid on your labels etc., and do not want to add the parentage, then adding "(hybrid)", "(F1)" or the like as an unranked intraspecfic part is the way I would do it.  Giving: "_Hosta_ 'Avacado' (hybrid)".  We, on occasion, use these "descriptive parts" in a name when they are common in the trade or where we have a unique form that's not named or the like.  e.g. "_Melaleuca viridiflora_ (red)" for a plant that produces particularly vibrant red flowers when the majority are creamy white to yellow-green.

**Comment by cwyse** [comment]
Hi -  Thanks for the great and detailed response.

I don't have a major need to specify 'hybrid' - I just wanted to do it properly, and not be confused about how to enter it.  I'm in good shape now.  Thanks for your help.
