### ISSUE TITLE
Accessions id for prior years

### ISSUE THREAD

**Issue by cwyse** [Ghini/ghini.desktop#467]
Sometimes I need to add an accession that belongs in a prior year, but I don't know what accession ID to use.  The editor shows the next ID for the current year, but if I type a prior year in the field, I'd like it to expand automatically to the next accession id for that prior year.  Instead, I need to find the number of accessions from that prior year and add one to it.

**Comment by mfrasca** [comment]
![image](https://user-images.githubusercontent.com/122869/77573161-3ddcf380-6e9e-11ea-9371-ad9cbd8500fe.png)

this is something we added a couple of years ago.
99ba74cd0088e583fae1aa3b1ca94d0bc75b1003

**Comment by mfrasca** [comment]
on second thought, it's not correct to close this, as it's still a hit on the documentation.

**Comment by cwyse** [comment]
Thanks.  I'll start using that.
