### ISSUE TITLE
Location support needed

### ISSUE THREAD

**Issue by cwyse** [Ghini/ghini.desktop#468]
Over the winter, my plant labels invariably get tossed around or go missing.  I go back to Ghini and have a list of the plants in the garden, but I don't have a good way to identify them within the garden.  It would be very useful to have a way to find plants from their database records in more granularity than which garden they reside in.

I know there are various schemes, a grid, location codes, sub codes, or others, but I'd like something that is built into the software.

**Comment by mfrasca** [comment]
this is one of the typical difficult problems in garden management.  I don't think I can offer you a software solution, and I am not aware of a single best practice that solves this once and for all.  if you choose your strategy, I can help you use the software to support it, but I would not want to build a specific strategy in the software, for other gardens might want a different one.

the suggestion I would give you is to keep location areas small (less than 40 plants), and to keep the finer details in notes.  but please let me know what "you dream of", maybe we already have it?

check also the [use cases](https://ghini.readthedocs.io/en/ghini-1.0-dev/use_cases.html) in the documentation.

**Comment by cwyse** [comment]
OK.  I leave it to your discretion on whether or not to leave this open or close it.   It's not really a bug - more of a request, so there might be a better spot to document it.

**Comment by mfrasca** [comment]
> I know there are various schemes, a grid, location codes, sub codes, or others, but I'd like something that is built into the software.

one schema I can advise is to impose a squares grid at all locations, it's something that some tiles servers use to name map tiles at increasing zoom depth.

you would add a `grid-position` note to your plants, and you need take care of doing so.  the `grid-position` is my hint for naming the notes category.

- the zoom depth determines the length of the code;
- at zoom zero, length zero, you are looking at the whole location.
- at each step you divide your area in 4 squares (clipping may be necessary)
- each step adds a character, 1, 2, 3 or 4, that tells you which of the four divisions is yours (1:NE, 2:NW, 3:SW, 4:SE).
- you decide if you need to divide further.

so for example:
2412 means NW, then SE, then NE, then NW, like here:
![image](https://user-images.githubusercontent.com/122869/106391673-8289c300-63bc-11eb-8219-2ae7f061ce95.png)

this schema has the advantage that grid-position with the same leading code are all together, like this would be grid-position=244, also in the tile 24.

![image](https://user-images.githubusercontent.com/122869/106391847-486cf100-63bd-11eb-82a3-a86c09810f41.png)

I'm closing this.  please feel free to reopen, or better share your solution as a contribution to the documentation.
