### ISSUE TITLE
Cannot install on ubuntu 20.04.1 LTS

### ISSUE THREAD

**Issue by kermesse** [Ghini/ghini.desktop#471]
The devinstall.sh installer script tries to install python-gtk2 that is not available on ubuntu 20.04.1 LTS. This is mostly due to the fact that python-gtk2 has been discontinued in favor of python3-pi. Import gi seems to fail as well. I suggest below a working workaround (forgive me the pun).

Suggested solution is to install ghini.desktop 3.1 through pip3, but be careful that if you try to do that at system level it may fail or overwrite essential packages. So this is the procedure I would suggest:

0) preliminary step: install libgirepository1.0-dev (from the terminal you can issue the command "sudo apt install libgirepository1.0-dev")
1) create a virtual environment. To do so: 
1.1) create a directory (I use Development/ghini/ghini.desktop)
1.2) enter the directory
1.3) open the terminal in the directory
1.4) issue the command "python3 -m venv ." 
2) in the terminal, activate the virtual environment using "source bin/activate"
3) still in the terminal, issue the following commands
3.1) pip install --upgrade pip
3.2) pip install wheel
3.3) pip install pycairo
3.4) pip install PyGObject
3.5) pip install psycopg2
3.5) pip install ghini.desktop
4) now you can run ghini using the command ghini from command line in the virtual environment
5) remember to always deactivate when you leave the virtual environment (command "deactivate")

**Comment by kermesse** [comment]
This is mostly due to the fact that python-gtk2 has been discontinued in favor of python3-pi.

**Comment by mfrasca** [comment]
hi @kermesse, thank you for opening this issue.  I do miss one point: which version of ghini.desktop are you trying to install?
you only mention 3.1, and 3.1 does not need python-gtk2, so if there's this dependency, it's out of place.

**Comment by kermesse** [comment]
Hi Mario, 

I first tried to install ghini 1.0.x, that failed and I was not able to solve the failure.

I then tried to install ghini 3.1.x, and that worked through the work around above. I am not sure why I had to do that to make it work because I did not have time to look into the code (very sorry for that!), and I only answered to the errors that the installation process was returning.

So, now 3.1.7 is working well on ubuntu 20.04.1, 1.0.x not working at all on ubuntu 20.04.1 but working on Windows 10, but unfortunately the databases are not compatible between the two releases, so we are using 3.1.7 with a new postgresql 13 database but we lost the data that were in the  SQLite database on 1.0.90. 

It happens!

  
 

> hi @kermesse, thank you for opening this issue. I do miss one point: which version of ghini.desktop are you trying to install?
> you only mention 3.1, and 3.1 does not need python-gtk2, so if there's this dependency, it's out of place.

**Comment by AndrewB53** [comment]
Hi @kermesse When I try this the champlain plug in doesn't install.

**Comment by mfrasca** [comment]
may I suggest: fix the installation script, if anything has to be fixed, and open a pull request.
textual instructions are often ambiguous.

**Comment by AndrewB53** [comment]
@mfrasca In the end I used the installation script and fixed the dependencies as they cropped up. So the 3.1 version is installed the next challenge is to copy the data from the version 1 db.

**Comment by mfrasca** [comment]
could you please double-check which script you have downloaded?  the script mentioning `python-gtk2` is the one in the ghini-1.0-dev branch.  the one in the ghini-3.1-dev branch will look for `python-gi`
for 3.1, the list of the dependencies checked by the script is:
gettext, python3-minimal, python3-gi, gir1.2-gtkclutter, gir1.2-gtkchamplain-0.12, python3-lxml, git,virtualenv,  libxslt1-dev, pkg-config, libjpeg-dev, build-essential, libpython3-all-dev

please do reopen the issue if you have indeed used the script from the ghini-3.1-dev branch.

**Comment by mfrasca** [comment]
> @mfrasca In the end I used the installation script and fixed the dependencies as they cropped up. So the 3.1 version is installed the next challenge is to copy the data from the version 1 db.

there is a very simple script for this, `bauble-upgrade-1.0-to-3.1.sh`, in the scripts directory.
use ghini-1.0 to export your data in CSV format, crunch the data through the script, import in an empty database.

**Comment by mfrasca** [comment]
> fixed the dependencies as they cropped up

next time, try to write down which dependencies cropped up, so we can put your experience in the script.
otherwise, you solved the issue on your computer, but the issue is still unresolved for all other users.
