### ISSUE TITLE
convert data from IrisDB to ghini desktop. 

### ISSUE THREAD

**Issue by thegreenman** [Ghini/ghini.desktop#473]
As a end user with some technical know-how, I want to import our current IrisDB data into Ghini Desktop, so that we can stop paying $1,000 per year in ongoing licensing fees.

**Comment by mfrasca** [comment]
Hi. and good news is this! a piece of request as I've been waiting for during no less than 8 years!
you need help to do that yourself, or you're willing to provide some financial help to the project while receiving the service?
the script for translating the information, and all documentation would become part of the technical documentation page.
write to one of the addresses published in the readthedocs pages, so we can talk.

**Comment by mfrasca** [comment]
hi again. I have never seen an IrisBG database, so strictly speaking I don't know what you're asking for. please do feel free to open again with some sample data.  as it stands, I have nothing to work upon.
