### ISSUE TITLE
copy about to be discontinued

### ISSUE THREAD

**Issue by mfrasca** [Ghini/ghini.desktop#49]
in our documentation I suggest the use of copy for sharing pictures.
the copy service is going to stop by July this year.
we need to correct the docs, either suggesting an alternative choice, or not mentioning this at all.
for institutions with an internal network, we can just suggest using a network 'share'.

**Comment by mfrasca** [comment]
@felipead87, @TatiJaramilloV, eso les va a afectar.

**Comment by TatiJaramilloV** [comment]
Y ahora????

Enviado desde mi iPhone

**Comment by mfrasca** [comment]
@TatiJaramilloV now we need choose an alternative and describe it in the docs.
one option you at the JBQ have, it could be to move your pictures to a network share.
the point is: Bauble/Ghini does not (yet) store pictures (not even thumbnails) in the database and relies on an external service to duplicate files among workstations. I think that Copy was a reasonable choice and with your amount of pictures (>3.5Gbytes) you could not have used the basic free Dropbox allowance.
if you need assistance for taking a decision at the JBQ, contact me on a chat, or let Felipe do so.

**Comment by mfrasca** [comment]
I've been testing [tresorit](http://tresorit.com/), a Swiss based service. they offer 5Gbyte free and their paid plans do not differ much from the competition. it's an easy installation on Linux.

**Comment by mfrasca** [comment]
Copy was discontinued, I've had the chance to visit the JBQ again, we chose for a local network solution, which is now also described in the docs. The JBQ now has a server with a Windows share, and clients with read/write rights. it works equally well on clients running Windows, GNU/Linux, OSX.
