### ISSUE TITLE
future direction

### ISSUE THREAD

**Issue by tmyersdn** [Ghini/ghini.desktop#50]
@RoDuth, Ross I'm guessing your not reading your email, but please do, it would help to have your comments.
@mfrasca, many thanks for your frank questions.

**Comment by mfrasca** [comment]
a lot seems to be moving in this period, too much to report here.
myself, I did not handle correctly with the climate change when moving back to Europe so I got immediately sick, and I'm not yet settled as to get back to work anyway.
I prefer closing this generic issue, please feel free to reopen with more specific info.
