### ISSUE TITLE
missing ghini.lnk

### ISSUE THREAD

**Issue by mfrasca** [Ghini/ghini.desktop#51]
I had removed the `bauble.lnk` file because it had hard coded paths in it and I forgot to open an issue related to the automatic generation of the corresponding Ghini file. now a new potential user mentions:

> I did the installation of `ghini.desktop` in my linux box and it works well. However I was not able to install it on Windows - giving an an error message linked to the missing `ghini.lnk` file in the script directory 
> `error: file 'C:\Users\USERNAME\Local\github\Ghini\ghini.desktop\scripts\ghini.lnk' does not exist`
> I would like to recommend to use the software in the K. University botanical garden, but would be much convenient to have it running on Windows.

**Comment by RoDuth** [comment]
I had one of my staff say that they would like a database for their home collection yesterday.  I said I have just the thing for you, bring your laptop in tomorrow and I'll install it for you....  Well I got all the way through the install on his Windows 10 setup... until the last bit that requires the ghini.lnk file!

Shouldn't I be able to run it from the command line anyway?  I can't seem to work out how and I'm worried there may be something else wrong with the install that I missed.

**Comment by mfrasca** [comment]
you can generate the ˙lnk˙ file easily from the gui. just a shortcut to the vbs script. then set the icon for it and re-run the last failing bit.

**Comment by mfrasca** [comment]
we can do this from Python, using pypiwin32 (should check the name). it would be a small script, like 10 lines. makes one wonder whether to drop the batch file entirely and do all from Python.

**Comment by mfrasca** [comment]
sorry it took such a long time. I am back to Europe, and obviously the first thing I did here was to get sick.
I have tested it and it works as advertised.
- download the `devinstall.bat` file
- run it
- run the `devinstall-finalize.bat` as administrator
- enjoy ghini from the windows menu

(please reopen if it does not work for you.)
