### ISSUE TITLE
genus editor window: hybrid flag isn't working

### ISSUE THREAD

**Issue by RoDuth** [Ghini/ghini.desktop#59]
OK, so I seem to have little time today and I'm not sure I will get much more time for a while.  And you did say you needed feed back @mfrasca :laughing:   
- In the genus editor window the hybrid flag isn't working.  The need for the nothotaxon flag here is great, not sure any of the other flags are of any use as they would be achieved at species editor level - with the new formula function, etc.  It must display the multiplication sign in the correct way of course and it would to have the option to list the genera that make the nothogenus (often multiple genera, with no particular formula, just a list)

---

> These are all, no doubt, bugs/issues you are aware of with 1.1 still in test mode but I thought I would record anyway.  Feel free to close the issue...
> - really obvious one... need a way to import data from v1.0 into the new database structure, (will have to wait for all the structure changes to be finalised first I guess) #65 
> - In the plant editor window changing the planting date does not make the OK button available, also I think planting date should be displayed in the right hand side info pane of the main search window. #64 
> - Accession `Identification Qualifier` doesn't display correctly in the info pane (i.e. if I enter _Archontophoenix ​alexandrae_ and put `?` as the `Identification Qualifier` and the `Qualified Rank` as _alexandrae_ it displays as _Archontophoenix_? _​alexandrae_ not _Archontophoenix_ ?_​alexandrae_ like I would normally expect to see) #63 

I think all the other things I noticed are already recorded in other issues.

**Comment by mfrasca** [comment]
was this related to the tests we were running for 1.1? or is this still related to 1.0?
I'm sorry I'm asking so much later, thinking that you opened this issue almost two years ago.
but as it now, I don't know where to start.
can you elaborate the "isn't working" into a step by step guide to reproduce what you observed?
if you can, please do, and reopen the issue. thank you so much. (and remove the 'invalid' flag).

**Comment by RoDuth** [comment]
I think your correct.  It related to 1.1.  Its been some time since I have looked at anything 1.1 so no idea if it's still the case but I think I remember it from the time.  Not having a hybrid flag for entering nothogenera (intergeneric hybrid genera) nor a method to record the list of genera that make up the nothotaxon (and hence a way to search for them by included genera) seems like a glaring omission from 1.0.  (Surely you have had this issue in the past?  Particularly when working with such promiscuous families as the orchids or bromeliads?)
