### ISSUE TITLE
add notes to location (model and view)

### ISSUE THREAD

**Issue by RoDuth** [Ghini/ghini.desktop#61]
Wish list item here.  

I would like to be able to make notes against locations.  In the same way as the species, accession and plant editors.  

I'd like it mainly be for generating management plans, so that you can make a note of category “management plan” which would be a broad statements about the design intent etc. of a garden (is it formal/informal, what style is it, any broad horticultural approaches to the area, etc. etc.) something a little more in depth than the general description.   "Management plan" notes would also exist at the other levels, e.g. at plant level it would have specific horticultural treatments for that specific plant (e.g. formal box hedge to 1.2m high, or raise lower limbs to create a shade tree, etc. etc.) and at species level it might have notes which would be relevant site wide on that species' requirements for fertilisers or susceptibility to pests etc. etc.. 

You could also make notes for a location about the irrigation system, the soil type in the area, the aspect, the infrastructure, etc. etc.

**Comment by mfrasca** [comment]
considering that searching by note content is less practical than grouping objects tagged with a common tag, I wonder if you really would use this for »_notes for a location about the irrigation system, the soil type in the area, the aspect, the infrastructure, etc. etc._« or would  you prefer using tags?

**Comment by RoDuth** [comment]
Tags don't allow detail.  This is definitely about the detail.  It would not be that you search by a note type/contents its that you would search by an area/species/etc. and then maybe generate a report about that object based on a note type.  

E.g. I want to know what station in the irrigation computer is our "Palm collection" on.   I search for "Palm collection" select the location and look for a note of type "irrigation" and it says what station and maybe what type of sprinklers etc. are in that area.
