### ISSUE TITLE
plant search result line not shown

### ISSUE THREAD

**Issue by mfrasca** [Ghini/ghini.desktop#68]
this was reported by @RoDuth 
![screenshot from 2016-03-03 17_37_53](https://cloud.githubusercontent.com/assets/122869/13546330/cfd497f4-e2aa-11e5-82d1-8444200db2cc.png)
> Comes and goes it seems but I haven't worked out the pattern and it never seems to go away for location 09.03.01.

I cannot duplicate the situation.
reported after updating with the commits related to #66, not necessarily related.

**Comment by mfrasca** [comment]
@RoDuth : please send me the log file (the screenshot I already have). the log file holds much more information that what you get on the terminal.

**Comment by RoDuth** [comment]
[bauble.log.zip](https://github.com/Ghini/ghini.desktop/files/166625/bauble.log.zip)
Days later it still displays as it does in the above screenshot.  Also, does it when I show the results of a recently made tag.  These 2 happen every time and I've noticed that, if they are the result of a wider search for instance, like 09.03 and I expand the 09.03.01 result and move the mouse over it they change.  It seems to change to whatever the mouse last hovered over.  like its some kind of refresh issue. 
 
![screenshot from 2016-03-10 16 51 16](https://cloud.githubusercontent.com/assets/15710055/13661661/694f9418-e6e0-11e5-9506-d8cc70408cb8.png)

Sometimes I can even get them to look garbled/illegible if I scroll too fast but I can't get a screenshot of that because as soon as the focus changes they go back to being legible.  Also, note the orange scroll bar and how it becomes fractured in appearance.

**Comment by mfrasca** [comment]
the log file does not contain anything other than 'DEBUG' info, meaning the software handles the problem hiding the fact it ever happened.
do you think you can create a log file by doing so little as possible?
like you (with minimal mouse movements—do not hover on things):
- start ghini
- search for '09.03'
- expand '09.03.01'
- select (click on) the first "expanded" row (a plant, but showing as the location)
- (the right hand side info box will show the info of the plant, or not)
- make a screenshot
- quit the program
- put here screenshot and zipped log file

**Comment by mfrasca** [comment]
if the above sequence of steps is not enough to reproduce the condition, do you think you could identify the minimal sequence necessary for doing so? note it down, then start ghini afresh, execute your sequence with the absolutely minimal mouse movements, take screenshots along the way (after every step. ideally, you would take a video of what is going on), quit the program and attach here the zipped log file, the sequence of steps you followed, the screenshots.

**Comment by RoDuth** [comment]
That was basically all I did last time.  But here, I search only for 09.03.01, expand it, select a plant, screenshot and close.
![screenshot from 2016-03-10 18 24 40](https://cloud.githubusercontent.com/assets/15710055/13663501/a8e33aaa-e6ed-11e5-849e-148616aa99f2.png)
[bauble.log.zip](https://github.com/Ghini/ghini.desktop/files/166751/bauble.log.zip)

**Comment by mfrasca** [comment]
I will need add some extra logging to the software. and ask you to upgrade to a temporary release. it won't be before your sleeping time so forget about it until tomorrow and have a good rest.

**Comment by RoDuth** [comment]
And another example...

Open, select Label 1 from the tags menu, select first entry, screenshot, close....

![screenshot from 2016-03-10 18 38 28](https://cloud.githubusercontent.com/assets/15710055/13663825/93d91718-e6ef-11e5-8070-a318cf3867fc.png)
[bauble.log.zip](https://github.com/Ghini/ghini.desktop/files/166771/bauble.log.zip)

**Comment by RoDuth** [comment]
Just so you know... I thought there may be a link between the 2 so I just deleted Label1 tag and it made no difference to 09.03.01

**Comment by mfrasca** [comment]
(while examining this issue, I noticed the introduction of 'None' rows in the result, it looks unrelated to the current issue, but it behaves similarly, in the sense that the search view would show one row which inherited the last computed valid row representation.)

**Comment by mfrasca** [comment]
@RoDuth, how can checkout `ghini-1.0-dev`?
activate the virtual environment, switch to the branch ghini-1.0-dev, pull all last information from github, run setup install.
you should be able to do all the above by just running:
`./scripts/devinstall.sh 1.0-dev`

or you do it by hand:
```bash
cd ~/Local/github/Ghini/ghini.desktop
source ~/.virtualenvs/ghide/bin/activate
git checkout ghini-1.0-dev
git pull
python setup.py install
```

(from your logs I fear your virtual environment is still named as `bacl`, not `ghide`. not so sure if that might be (a | part of the) problem.)

**Comment by RoDuth** [comment]
@mfrasca Sorry, have been **really busy** with other matters....

Did as you advise above and here are the results:

![screenshot from 2016-03-15 20 12 24](https://cloud.githubusercontent.com/assets/15710055/13774474/fe8c5a08-eaea-11e5-8a3f-d1e8d795d508.png)

[bauble.log.zip](https://github.com/Ghini/ghini.desktop/files/173660/bauble.log.zip)

Just as a wild card suggestion here....  Is it possible that the data itself has become corrupted?  When I first noticed this was after copying the SQLite database file over to my home computer (we still have not upgraded at work from an old Bauble version).  I have a vague memory of having to xkill Ghini at some point as it had become frozen but am not entirely sure when I did it.  The only older version I have at hand is quite a bit older prior to the addition of plants to 09.03.01.

**Comment by mfrasca** [comment]
@RoDuth , I do not know what to think. I had expected several "TBR" logging records (to be removed), but I see none, so I still don't know what is going on there. if it is a sqlite database, can you send it to me somehow? like you put it on dropbox or tresorit or even google drive, and send me a link to it?

**Comment by RoDuth** [comment]
They tell me they almost have Ghini ready to install at work.  I'll wait and see how it goes there.  (we have added a few hundred more records in the last few weeks on the old Bauble v1.0.11 and its still running fine so I'd rather wait and see.  If there are problems I'll send the newer version)

**Comment by mfrasca** [comment]
@RoDuth , I'm not able to reproduce the issue reported here, and I cannot see anything in the logs you posted. if you fear this might happen at your office, then please do not upgrade to the latest ghini there.
if you are able to send me somehow (google drive? dropbox? tresorit?) the broken database, then I might be able to examine the issue.
staying things like they are now, I am not looking into it further.
