### ISSUE TITLE
accession editor: OK button not activated after valid edit

### ISSUE THREAD

**Issue by RoDuth** [Ghini/ghini.desktop#76]
When using `Source` > `Propogation of Source Material`

It seems to be fine for seed and unrooted cuttings but stops you from being able to click OK, as if you haven't filed in a required field, if the propagation type is blank or set to other.  I would like to use "other" when a whole plant is collected just to make a note to say that we collected it, kept it for a few days and then planted it in situ in the garden and other similar uses.

**Comment by RoDuth** [comment]
e.g.
![screenshot from 2016-03-19 19 52 05](https://cloud.githubusercontent.com/assets/15710055/13897870/2a07d3dc-ee0c-11e5-9787-11581e82c971.png)


OK button only becomes unavailable after selecting `Other`.

Also... there's a typo there in "Pro**g**agation Type"

**Comment by mfrasca** [comment]
> OK button only becomes unavailable after selecting Other.

indeed, when you select 'Other' propagation type, there's no way to click on OK.
I'm looking into it. it's not difficult solving this initial part, but then somehow there's a seed propagation wanting to be inserted, and that isn't possible unless you specify its parameters.

**Comment by mfrasca** [comment]
part of the problem was behind this comment: 

        # TODO: this function is not ideal since it just duplicates
        # PropagationEditor.clean_model()...we need a sensible way to
        # share this code

and there was a rather straightforward solution to it, just implement the functionality in the correct class, in this case the Propagation. Then the different presenters —owning a model of the same class— can invoke the model's method.
