### ISSUE TITLE
Plant Editor: Auto-fill for Location no longer working

### ISSUE THREAD

**Issue by RoDuth** [Ghini/ghini.desktop#77]
Just went to add a plant and, as I would normally do at work (old v 1.0.11 Bauble), clicked into the location field and started typing and nothing happened.   Our list of locations is huge at almost 400 and auto-fill is the only way to use it.  Usually I just typing the "code" number.

**Comment by mfrasca** [comment]
hi @RoDuth . this with 1.0, isn't it?

**Comment by RoDuth** [comment]
Yes.

**Comment by mfrasca** [comment]
I hope to be able to have a look at this, together with #76, #71, (you had questions related to #66), #55, #45, and the currently most complex one #68, which I can now reproduce here. let's just hope I fix all pending logistic issues soon so I can get back to work. :sweat:
