### ISSUE TITLE
Icon based on habitus

### ISSUE THREAD

**Issue by smbantjes** [Ghini/ghini.desktop#82]
It would be nice if there were different icons based on habitus for different types of plants (tree, palm, shrub, smaller plants).

I have a map of the 3 greenhouses, all divided in subareas. I would like to locate plants in the map and that it is clear what type of plant it is even before I click on the icon and get the complete information.

**Comment by mfrasca** [comment]
Hi @smbantjes , this is a relevant issue, thanks for opening it, and it is two issues in one, since you are really also telling me to please publish ghini.web in the Ghini organization, while it is now only in a temporary repository as [mfrasca/ghini](http://github.com/mfrasca/ghini).

**Comment by mfrasca** [comment]
in the meanwhile, I have plant icon based on genus or family, and it's part of ghini.web.
