### ISSUE TITLE
defaults in plant insertion window

### ISSUE THREAD

**Issue by mfrasca** [Ghini/ghini.desktop#91]
_From @mfrasca on June 2, 2015 13:55_

_From @mfrasca on February 14, 2014 12:37_

while (repeatedly) inserting plants, some selections could keep the last used value as default, for example 'location'.

_Copied from original issue: mfrasca/bauble.classic#4_

_Copied from original issue: Bauble/bauble.classic#51_

**Comment by mfrasca** [comment]
Eric Gouda of the BTUU gave an interesting hint: offer the user the possibility to save the status of an "Editor" (that is a ghini term) into a buffer, like pressing a key combination that could be Ctrl-Shift-C, and to paste it back into the same editor by the key combination Ctrl-Shift-V.
each "Editor" would have its own clipboard, so that saving the status of the species editor would not impact the plant or the accession editors.

**Comment by RoDuth** [comment]
Now this I like a lot, especially if you can expand the idea to such things as the collection info in the source pane in the accession editor. Would solve the issue I've mentioned before when you have 20 accessions all from one collection trip from one site, all with the same location info (Lat/Long/Alt/Habitat/etc.).  Entering that for every accession is very tedious!

**Comment by mfrasca** [comment]
as soon as I get back to work on Ghini, I will start handling all issues that I have "assigned" to me. this is included, maybe not "top of the list" but it is included.

**Comment by mfrasca** [comment]
steps here:
- add a buffer to the presenter of each editor,
- define two actions per editor that will copy the status to the local buffer,
- associate the actions to C-S-c & C-S v, respectively,

what else ... ?

**Comment by mfrasca** [comment]
I was looking into how to create custom signals, but we don't really need that, we just need two actions, 
define their accelerators, put them in an action group, associate the action group to the GtkDialog that's the root widget.

if we were using glade:

    <object class="GtkAction" id="action_window_clip_paste">
      <signal name="activate" handler="on_clip_paste" swapped="no"/>
    </object>
    <object class="GtkAction" id="action_window_clip_copy">
      <signal name="activate" handler="on_clip_copy" swapped="no"/>
    </object>

but we would need this in every glade file, while we want this behaviour in all windows, so we're going to program it in the constructor of the generic presenter.

**Comment by mfrasca** [comment]
wow, it looks like it wasn't that difficult after all, that is, once we cleared how to do it.
https://stackoverflow.com/a/48312512/78912
now we have to make sure we don't overwrite **every** field, like we don't want to overwrite the ones we already entered, or there's a selection of fields we never overwrite, and it depends on the class of the model. I think the easiest is "don't overwrite", but we can talk about it.

**Comment by mfrasca** [comment]
I spoke too early: at the moment it works only for single page editors, not for editors with notebooks. with notebooks, there's only one book visible at all time, so when a user is copying the view, they want to copy those visible fields into the clipboard. conversely, when pasting from the clipboard, they would be surprised to see fields in every book overwritten with the copied values.
so I think we keep one action per GtkDialog, and let it act on all registered books. every presenter registers a callback with a book. maybe something like this.

**Comment by mfrasca** [comment]
provo ad iniziare dal comportamento desiderato, non dal come organizzare i dati.
quando l'utente preme C-S-c o C-S-v, l'oggetto `gtk.Action` corrispondente cerca se nella vista a cui appartiene esiste un elemento di nome 'notebook' o meno.
se non esiste è più semplice, perché la pagina principale è la pagina visibile.
se esiste, deve chiedere al notebook quale sua pagina sia visibile, ed è una sola.
ora stiamo con una pagina visibile, che ha un nome.

l'azione `<ctrl><shift>v` deve poter associare a ciascun nome una lista di presenter di cui invocare il metodo `paste_values`.
il metodo `paste` di ciascun presenter fa sempre la stessa cosa e può stare nella classe base: per ciascun widget che non sia stato modificato manualmente, cambiare il suo valore a quello corrispondente nel clipboard. la lista dei widget da verificare sta nel campo `widget_to_field_map`.

anche l'azione `<ctrl><shift>c` associa a ciascun nome una lista di presenter di cui invocare il metodo `copy_values` ed anche questa azione è generica.

a questo punto sappiamo cosa deve fare il presenter durante l'inizializzazione: registrarsi come presenter con clipboard.

**Comment by Ejgouda** [comment]
Mario,

Get me from this loop!

Eric


Op 23-01-18 om 21:43 schreef Mario Frasca:

**Comment by mfrasca** [comment]
@Ejgouda , so sorry to hear that this is getting to your nerves, obviously never the intention.
you're the only one who can switch off notifications for your own account.
you can do it just from this issue here,
![image](https://user-images.githubusercontent.com/122869/35467454-58a6b834-02dc-11e8-83e1-67f69c893aab.png)
but I guess much better if you tune your global preferences.

**Comment by mfrasca** [comment]
we have a video showing this at work
https://youtu.be/Bo4n7qX8v7c
